import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ru" | "uz" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Extended Translations
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Greetings
    "greeting.morning": "Доброе утро",
    "greeting.afternoon": "Добрый день",
    "greeting.evening": "Добрый вечер",
    
    // Settings
    "settings.title": "Настройки",
    "settings.theme": "Тема",
    "settings.language": "Язык",
    "settings.notifications": "Уведомления",
    "settings.privacy": "Конфиденциальность",
    "settings.security": "Безопасность",
    "settings.account": "Аккаунт",
    
    // Common
    "common.loading": "Загрузка...",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.submit": "Отправить",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.export": "Экспорт",
    "common.currency": "сўм",
    "common.usd": "USD",
    "common.km": "км",
    "common.kg": "кг",
    "common.close": "Закрыть",
    "common.confirm": "Подтвердить",
    "common.all": "Все",
    "common.today": "Сегодня",
    "common.yesterday": "Вчера",
    "common.week": "Неделя",
    "common.month": "Месяц",
    "common.error": "Ошибка",
    "common.success": "Успешно",
    
    // Auth
    "auth.login": "Войти",
    "auth.logout": "Выйти",
    "auth.register": "Регистрация",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.forgotPassword": "Забыли пароль?",
    "auth.noAccount": "Нет аккаунта?",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.createAccount": "Создать аккаунт",
    
    // Navigation
    "nav.home": "Главная",
    "nav.dashboard": "Панель управления",
    "nav.profile": "Профиль",
    "nav.orders": "Заказы",
    "nav.deals": "Сделки",
    "nav.settings": "Настройки",
    "nav.admin": "Админ-панель",
    
    // Roles
    "role.client": "Клиент",
    "role.carrier": "Перевозчик",
    "role.admin": "Администратор",
    "role.driver": "Водитель",
    "role.company": "Компания",
    
    // Dashboard
    "dashboard.myDeals": "Мои сделки",
    "dashboard.noDeals": "У вас пока нет активных сделок",
    "dashboard.deals": "сделок",
    "dashboard.welcome": "Добро пожаловать",
    "dashboard.subtitle.client": "Создайте заявку и найдите перевозчика",
    "dashboard.subtitle.carrier": "Найдите заказы в вашем регионе",
    "dashboard.subtitle.admin": "Управляйте платформой",
    
    // Orders
    "orders.create": "Создать заявку",
    "orders.myOrders": "Мои заявки",
    "orders.available": "Доступные заказы",
    "orders.cargoType": "Тип груза",
    "orders.weight": "Вес",
    "orders.dimensions": "Габариты",
    "orders.pickupAddress": "Адрес погрузки",
    "orders.deliveryAddress": "Адрес доставки",
    "orders.pickupDate": "Дата погрузки",
    "orders.description": "Описание",
    "orders.price": "Цена",
    "orders.clientPrice": "Ваша цена",
    "orders.newOrder": "Новая заявка",
    "orders.fillInfo": "Заполните информацию о грузе и маршруте",
    "orders.selectRegion": "Выберите регион",
    "orders.selectCity": "Выберите город",
    "orders.region": "Регион",
    "orders.city": "Город",
    "orders.cargoPhoto": "Фото груза",
    "orders.comment": "Комментарий",
    "orders.priceHint": "Перевозчики увидят вашу цену",
    "orders.status.open": "Открыта",
    "orders.status.in_progress": "В работе",
    "orders.status.completed": "Завершена",
    "orders.status.cancelled": "Отменена",
    "orders.createNew": "Новая заявка",
    "orders.pickupAddressFull": "Полный адрес погрузки",
    
    // Carrier
    "carrier.stats": "Статистика перевозчика",
    "carrier.history": "Ваша история и достижения",
    "carrier.completed": "Выполнено",
    "carrier.earned": "Заработано",
    "carrier.rating": "Рейтинг",
    "carrier.inProgress": "В работе",
    "carrier.completionRate": "Завершённость",
    "carrier.ordersCompleted": "заказов выполнено",
    "carrier.yourRating": "Ваш рейтинг",
    "carrier.reviews": "отзывов",
    "carrier.thisMonth": "В этом месяце",
    "carrier.orders": "Заказов",
    "carrier.cancelled": "Отменено",
    "carrier.achievements": "Достижения",
    "carrier.unlocked": "Разблокировано",
    "carrier.of": "из",
    "carrier.nextAchievements": "Следующие достижения",
    "carrier.preferences": "Настройки уведомлений",
    "carrier.respond": "Откликнуться",
    "carrier.responded": "Вы откликнулись",
    "carrier.viewDetails": "Подробнее",
    "carrier.navigation": "Навигация",
    "carrier.myResponses": "Мои отклики",
    
    // Favorites
    "favorites.title": "Избранные",
    "favorites.carriers": "Избранные перевозчики",
    "favorites.empty": "У вас пока нет избранных перевозчиков",
    
    // Stats
    "stats.outOf": "из",
    "stats.noRating": "Нет отзывов",
    "stats.excellent": "Отлично",
    "stats.good": "Хорошо",
    "stats.average": "Средне",
    "stats.poor": "Плохо",
    
    // Levels
    "level.beginner": "Новичок",
    "level.experienced": "Опытный",
    "level.professional": "Профессионал",
    "level.expert": "Эксперт",
    "level.yourLevel": "Ваш уровень",
    "level.privileges": "Привилегии",
    "level.nextLevel": "До следующего уровня",
    "level.dealsNeeded": "заказов",
    "level.priorityOrders": "Приоритетные заказы",
    "level.reducedCommission": "Сниженная комиссия",
    "level.verifiedBadge": "Значок проверенного",
    "level.premiumSupport": "Премиум поддержка",
    "level.topPlacement": "Топ размещение",
    "level.exclusiveOffers": "Эксклюзивные предложения",
    
    // Deals
    "deals.myDeals": "Мои сделки",
    "deals.status.pending": "Ожидает",
    "deals.status.accepted": "Принята",
    "deals.status.in_transit": "В пути",
    "deals.status.delivered": "Доставлено",
    "deals.status.cancelled": "Отменена",
    "deals.chat": "Чат",
    "deals.driver": "Перевозчик",
    "deals.client": "Клиент",
    "deals.accept": "Принять",
    "deals.reject": "Отклонить",
    "deals.startDelivery": "Начать доставку",
    "deals.completeDelivery": "Завершить доставку",
    "deals.cancel": "Отменить сделку",
    
    // Negotiation
    "negotiation.title": "Торг по цене",
    "negotiation.clientPrice": "Цена клиента",
    "negotiation.currentPrice": "Текущая цена",
    "negotiation.waitingResponse": "Ожидает ответа",
    "negotiation.accepted": "Принято",
    "negotiation.rejected": "Отклонено",
    "negotiation.priceAgreed": "Цена согласована",
    "negotiation.proposePrice": "Предложить цену",
    "negotiation.yourPrice": "Ваша цена",
    "negotiation.comment": "Комментарий (необязательно)",
    "negotiation.propose": "Предложить",
    
    // Chat
    "chat.writeMessage": "Напишите сообщение...",
    "chat.send": "Отправить",
    "chat.systemMessage": "Системное сообщение",
    "chat.noMessages": "Нет сообщений",
    "chat.startConversation": "Начните диалог",
    
    // Calculator
    "calculator.title": "Калькулятор доставки",
    "calculator.description": "Рассчитайте стоимость между городами Центральной Азии",
    "calculator.from": "Откуда",
    "calculator.to": "Куда",
    "calculator.selectCity": "Выберите город",
    "calculator.cargoWeight": "Вес груза",
    "calculator.vehicleType": "Тип транспорта",
    "calculator.currency": "Валюта",
    "calculator.distance": "Расстояние",
    "calculator.basePrice": "Базовая цена",
    "calculator.distancePrice": "Расстояние",
    "calculator.weightPrice": "Вес",
    "calculator.vehicleSurcharge": "Надбавка транспорта",
    "calculator.borderFee": "Пошлина границы",
    "calculator.totalPrice": "Итого",
    "calculator.internationalShipping": "Международная перевозка",
    "calculator.approximatePrice": "Примерная цена",
    "calculator.exchangeRate": "Курс",
    
    // Map
    "map.route": "Маршрут",
    "map.showOnMap": "Показать на карте",
    "map.optimalRoute": "Оптимальный маршрут",
    "map.liveTracking": "Отслеживание в реальном времени",
    "map.driverLocation": "Местоположение водителя",
    "map.estimatedArrival": "Расчётное время прибытия",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Язык",
    
    // Landing Page
    "landing.hero.badge": "Логистика Центральной Азии",
    "landing.hero.title": "Грузоперевозки",
    "landing.hero.titleHighlight": "нового поколения",
    "landing.hero.subtitle": "Соединяем клиентов, водителей и логистические компании в Узбекистане, Казахстане, Кыргызстане, Таджикистане и Туркменистане",
    "landing.hero.cta": "Начать бесплатно",
    "landing.hero.demo": "Смотреть демо",
    "landing.hero.deliveries": "Перевозок",
    "landing.hero.drivers": "Водителей",
    "landing.hero.rating": "Рейтинг",
    
    "landing.features.title": "Всё для успешной логистики",
    "landing.features.subtitle": "Мощные инструменты для всех участников процесса",
    "landing.features.chat": "Умные чаты",
    "landing.features.chatDesc": "Общий чат до сделки и отдельный чат для каждой сделки",
    "landing.features.security": "Безопасность",
    "landing.features.securityDesc": "Верификация документов и защищённые транзакции",
    "landing.features.ratings": "Рейтинги",
    "landing.features.ratingsDesc": "Двусторонние оценки после каждой сделки",
    "landing.features.analytics": "Аналитика",
    "landing.features.analyticsDesc": "Графики активности и статистика сделок",
    "landing.features.roles": "3 роли",
    "landing.features.rolesDesc": "Клиенты, водители и компании",
    "landing.features.fast": "Быстрый старт",
    "landing.features.fastDesc": "Регистрация за минуту, первая заявка — за 5 минут",
    
    "landing.roles.title": "Платформа для каждого",
    "landing.roles.subtitle": "Три типа пользователей — единая экосистема доверия",
    "landing.roles.clientDesc": "Человек или бизнес, которому нужно перевезти груз",
    "landing.roles.driverDesc": "Независимый водитель с личным транспортом",
    "landing.roles.companyDesc": "Логистическая компания с командой водителей",
    "landing.roles.startAs": "Начать как",
    "landing.roles.clientF1": "Создание заявок за минуты",
    "landing.roles.clientF2": "Выбор водителя или компании",
    "landing.roles.clientF3": "Чат и отслеживание",
    "landing.roles.clientF4": "Оценка исполнителей",
    "landing.roles.driverF1": "Просмотр актуальных заявок",
    "landing.roles.driverF2": "Гибкий график работы",
    "landing.roles.driverF3": "Прямая связь с клиентом",
    "landing.roles.driverF4": "Рост рейтинга и дохода",
    "landing.roles.companyF1": "Управление автопарком",
    "landing.roles.companyF2": "Распределение заказов",
    "landing.roles.companyF3": "Аналитика и отчёты",
    "landing.roles.companyF4": "Единый корпоративный рейтинг",
    
    "landing.flow.title": "Как работает сделка",
    "landing.flow.subtitle": "Простой и прозрачный процесс от заявки до доставки",
    "landing.flow.step": "Шаг",
    "landing.flow.order": "Заявка",
    "landing.flow.orderDesc": "Клиент создаёт заявку на перевозку",
    "landing.flow.response": "Отклик",
    "landing.flow.responseDesc": "Водитель или компания откликается",
    "landing.flow.negotiation": "Согласование",
    "landing.flow.negotiationDesc": "Обсуждение условий в чате",
    "landing.flow.deal": "Сделка",
    "landing.flow.dealDesc": "Клиент подтверждает — создаётся чат сделки",
    "landing.flow.delivery": "Доставка",
    "landing.flow.deliveryDesc": "Груз в пути с обновлением статуса",
    "landing.flow.rating": "Оценка",
    "landing.flow.ratingDesc": "Взаимные оценки после завершения",
    
    "landing.trust.badge": "Система доверия",
    "landing.trust.title": "Система доверия",
    "landing.trust.subtitle": "Чем больше успешных сделок — тем выше ваш статус",
    "landing.trust.bronze": "Бронза",
    "landing.trust.bronzeReq": "Первые шаги",
    "landing.trust.silver": "Серебро",
    "landing.trust.silverReq": "Проверенный участник",
    "landing.trust.gold": "Золото",
    "landing.trust.goldReq": "Топ исполнитель",
    "landing.trust.protection": "Защита от накруток — оценки только после сделок",
    
    "landing.cta.badge": "Бесплатный старт",
    "landing.cta.title": "Готовы начать?",
    "landing.cta.subtitle": "Присоединяйтесь к AsiaLog и откройте новые возможности",
    "landing.cta.create": "Создать аккаунт",
    "landing.cta.contact": "Связаться с нами",
    "landing.cta.free": "Бесплатная регистрация",
    "landing.cta.noHidden": "Без скрытых платежей",
    
    "landing.footer.product": "Продукт",
    "landing.footer.company": "Компания",
    "landing.footer.resources": "Ресурсы",
    "landing.footer.legal": "Правовая информация",
    "landing.footer.features": "Возможности",
    "landing.footer.pricing": "Тарифы",
    "landing.footer.api": "API",
    "landing.footer.about": "О нас",
    "landing.footer.careers": "Карьера",
    "landing.footer.blog": "Блог",
    "landing.footer.docs": "Документация",
    "landing.footer.support": "Поддержка",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Условия",
    "landing.footer.privacy": "Конфиденциальность",
    "landing.footer.rights": "Все права защищены",
    "landing.footer.description": "Логистическая платформа для Центральной Азии",
    
    // Admin Panel
    "admin.title": "Админ-панель",
    "admin.analytics": "Аналитика",
    "admin.users": "Пользователи",
    "admin.deals": "Сделки",
    "admin.promos": "Промокоды",
    "admin.aiChat": "AI Чат",
    "admin.totalOrders": "Всего заказов",
    "admin.totalDeals": "Всего сделок",
    "admin.totalUsers": "Пользователей",
    "admin.revenue": "Выручка",
    "admin.avgRating": "Средний рейтинг",
    "admin.growth": "Рост за неделю",
    "admin.verified": "Верифицировано",
    "admin.pending": "На проверке",
    "admin.verify": "Верифицировать",
    "admin.unverify": "Снять верификацию",
    "admin.newPromo": "Новый промокод",
    "admin.promoCode": "Код",
    "admin.discount": "Скидка",
    "admin.usage": "Использований",
    "admin.active": "Активен",
    
    // Regions
    "region.uzbekistan": "Узбекистан",
    "region.kazakhstan": "Казахстан",
    "region.kyrgyzstan": "Кыргызстан",
    "region.tajikistan": "Таджикистан",
    "region.turkmenistan": "Туркменистан",
    "region.afghanistan": "Афганистан",
    
    // Promo
    "promo.title": "Промокод",
    "promo.apply": "Применить",
    "promo.applied": "Промокод применён",
    "promo.invalid": "Недействительный промокод",
    "promo.expired": "Промокод истёк",
    "promo.alreadyUsed": "Вы уже использовали этот промокод",
    
    // Notifications
    "notifications.title": "Уведомления",
    "notifications.empty": "Нет уведомлений",
    "notifications.markRead": "Отметить прочитанным",
    "notifications.markAllRead": "Прочитать все",
    
    // Navigation
    "navigation.title": "Навигация",
    "navigation.openNavigator": "Открыть навигатор",
    "navigation.fullNavigation": "Полная навигация",
    "navigation.buildRoute": "Построить маршрут",
    "navigation.followMe": "Следовать за мной",
    "navigation.startNavigation": "Начать навигацию",
    "navigation.stopNavigation": "Остановить",
    "navigation.recalculate": "Пересчитать",
    "navigation.arrival": "Прибытие",
    "navigation.distance": "Расстояние",
    "navigation.duration": "Время в пути",
    "navigation.traffic": "С учётом пробок",
    "navigation.noTraffic": "Без пробок",
    "navigation.fastest": "Самый быстрый",
    "navigation.shortest": "Самый короткий",
    "navigation.alternative": "Альтернативный",
    "navigation.selectRoute": "Выбрать маршрут",
    "navigation.routeDetails": "Детали маршрута",
    "navigation.steps": "шагов",
    "navigation.driving": "На машине",
    "navigation.walking": "Пешком",
    "navigation.voiceEnabled": "Голос включён",
    "navigation.voiceDisabled": "Голос выключен",
    "navigation.offlineMode": "Офлайн режим",
    "navigation.downloadMap": "Скачать карту",
    "navigation.mapDownloaded": "Карта скачана",
    "navigation.cacheRoute": "Кэшировать маршрут",
    "navigation.speedCamera": "Камера контроля скорости",
    "navigation.speedLimit": "Ограничение скорости",
    "navigation.ahead": "впереди",
    "navigation.meters": "м",
    "navigation.km": "км",
    "navigation.hours": "ч",
    "navigation.minutes": "мин",
    "navigation.yourSpeed": "Ваша скорость",
    "navigation.heading": "Курс",
    
    // Deal Chat
    "dealChat.title": "Чат сделки",
    "dealChat.error": "Ошибка",
    "dealChat.dealNotFound": "Сделка не найдена",
    "dealChat.accessDenied": "Доступ запрещён",
    "dealChat.notParticipant": "Вы не являетесь участником этой сделки",
    "dealChat.statusUpdated": "Статус обновлён",
    "dealChat.updateFailed": "Не удалось обновить статус",
    "dealChat.acceptOrder": "Принять заказ",
    "dealChat.carrierAccepted": "Перевозчик принял заказ",
    "dealChat.startDelivery": "Начать доставку",
    "dealChat.cargoInTransit": "Груз в пути",
    "dealChat.completeDelivery": "Завершить доставку",
    "dealChat.cargoDelivered": "Груз доставлен!",
    "dealChat.cancelDeal": "Отменить сделку",
    "dealChat.cancelQuestion": "Отменить сделку?",
    "dealChat.cancelDescription": "Сделка будет отменена, а заявка снова станет доступна для других перевозчиков. Вторая сторона получит уведомление об отмене.",
    "dealChat.cancelReason": "Причина отмены",
    "dealChat.cancelReasonPlaceholder": "Укажите причину отмены сделки...",
    "dealChat.dealCancelled": "Сделка отменена",
    "dealChat.orderAvailable": "Заявка снова доступна для других перевозчиков",
    "dealChat.cancelFailed": "Не удалось отменить сделку",
    "dealChat.cancelling": "Отмена...",
    "dealChat.participant": "Участник",
    "dealChat.priceUpdated": "Цена обновлена",
    "dealChat.newAgreedPrice": "Новая согласованная цена",
    "dealChat.yourReview": "Ваш отзыв",
    "dealChat.reviewFrom": "Отзыв от",
    "dealChat.carrier": "Перевозчик",
    "dealChat.client": "Клиент",
    
    // Errors
    "error.generic": "Произошла ошибка",
    "error.tryAgain": "Попробуйте снова",
    "error.notFound": "Не найдено",
    "error.unauthorized": "Нет доступа",
    "error.networkError": "Ошибка сети",
    "error.serverError": "Ошибка сервера",
    
    // Success
    "success.saved": "Сохранено",
    "success.updated": "Обновлено",
    "success.deleted": "Удалено",
    "success.created": "Создано",
    
    // Confirmation
    "confirm.areYouSure": "Вы уверены?",
    "confirm.thisCannotBeUndone": "Это действие нельзя отменить.",
    "confirm.yes": "Да",
    "confirm.no": "Нет",
    
    // Profile
    "profile.title": "Профиль",
    "profile.myProfile": "Мой профиль",
    "profile.userProfile": "Профиль пользователя",
    "profile.editProfile": "Редактирование профиля",
    "profile.updateInfo": "Обновите информацию о себе",
    "profile.clickToUpload": "Нажмите для загрузки фото",
    "profile.name": "Имя",
    "profile.phone": "Телефон",
    "profile.companyName": "Название компании",
    "profile.vehicleType": "Тип транспорта",
    "profile.saving": "Сохранение...",
    "profile.avatarUpdated": "Аватар обновлён",
    "profile.newPhotoSaved": "Новое фото профиля сохранено",
    "profile.uploadError": "Ошибка загрузки",
    "profile.uploadFailed": "Не удалось загрузить изображение",
    "profile.profileUpdated": "Профиль обновлён",
    "profile.changesSaved": "Изменения успешно сохранены",
    "profile.saveFailed": "Не удалось сохранить изменения",
    "profile.wrongFormat": "Неверный формат",
    "profile.selectImage": "Пожалуйста, выберите изображение",
    "profile.fileTooLarge": "Файл слишком большой",
    "profile.maxFileSize": "Максимальный размер файла — 5 МБ",
    "profile.notFound": "Профиль не найден",
    "profile.noName": "Без имени",
    "profile.verified": "Верифицирован",
    "profile.onPlatformSince": "На платформе с",
    "profile.company": "Компания",
    "profile.vehicle": "Транспорт",
    "profile.totalDeals": "Всего сделок",
    "profile.completed": "Завершено",
    "profile.active": "Активных",
    "profile.rating": "Рейтинг",
    "profile.ratingDistribution": "Распределение оценок",
    "profile.reviews": "Отзывы",
    "profile.verification": "Верификация",
    "profile.noReviewsYet": "У пользователя пока нет отзывов",
    "profile.reviewsCount": "отзывов",
    "profile.review": "отзыв",
    "profile.user": "Пользователь",
    
    // Orders List
    "ordersList.myOrders": "Мои заявки",
    "ordersList.totalOrders": "Всего заявок",
    "ordersList.noOrdersYet": "У вас пока нет заявок",
    "ordersList.createFirstOrder": "Создайте первую заявку выше",
    "ordersList.loadingOrders": "Загрузка заявок...",
    "ordersList.responses": "откликов",
    "ordersList.photos": "фото",
    "ordersList.canEdit": "Можно изменить",
    "ordersList.details": "Подробнее",
    "ordersList.cancelOrder": "Отменить",
    "ordersList.cancelOrderTitle": "Отменить заявку?",
    "ordersList.cancelOrderDesc": "Вы уверены, что хотите отменить эту заявку? Это действие нельзя отменить. Все отклики перевозчиков будут отклонены.",
    "ordersList.dontCancel": "Не отменять",
    "ordersList.yesCancel": "Да, отменить",
    "ordersList.orderCancelled": "Заявка отменена",
    "ordersList.orderCancelledDesc": "Ваша заявка была успешно отменена",
    "ordersList.cancelFailed": "Не удалось отменить заявку",
    
    // AI Chat
    "aiChat.title": "AI Помощник",
    "aiChat.subtitle": "Выбор перевозчика и расчёт",
    "aiChat.clearChat": "Очистить чат",
    "aiChat.greeting": "Привет! Я помогу выбрать перевозчика и рассчитать стоимость доставки.",
    "aiChat.historySaved": "История сохраняется автоматически",
    "aiChat.askQuestion": "Задайте вопрос...",
    "aiChat.rateResponse": "Оцените ответ:",
    "aiChat.quickQuestion1": "Как рассчитать стоимость?",
    "aiChat.quickQuestion2": "Какой перевозчик лучше?",
    "aiChat.quickQuestion3": "Сколько стоит срочная доставка?",
    
    // Auth Page
    "auth.backToHome": "На главную",
    "auth.platformName": "LogiFlow",
    "auth.platformDesc": "Платформа для грузоперевозок",
    "auth.loginTab": "Вход",
    "auth.registerTab": "Регистрация",
    "auth.loggingIn": "Вход...",
    "auth.registering": "Регистрация...",
    "auth.selectRole": "Выберите роль",
    "auth.iOrderDelivery": "Заказываю перевозки",
    "auth.iExecuteOrders": "Выполняю заказы",
    "auth.referralCode": "Реферальный код (необязательно)",
    "auth.enterFriendCode": "Введите код друга",
    "auth.codeValid": "Код действителен",
    "auth.codeNotFound": "Код не найден",
    "auth.registerAs": "Зарегистрироваться как",
    "auth.orFullRegistration": "или",
    "auth.fullRegistration": "пройти полную регистрацию →",
    "auth.validationError": "Ошибка валидации",
    "auth.loginError": "Ошибка входа",
    "auth.loginFailed": "Произошла ошибка при входе",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.emailNotConfirmed": "Email не подтверждён",
    "auth.welcome": "Добро пожаловать!",
    "auth.loginSuccess": "Вы успешно вошли в систему",
    "auth.registrationError": "Ошибка регистрации",
    "auth.registrationFailed": "Произошла ошибка при регистрации",
    "auth.emailAlreadyRegistered": "Этот email уже зарегистрирован",
    "auth.registrationSuccess": "Регистрация успешна!",
    "auth.welcomeToPlatform": "Добро пожаловать в LogiFlow",
    "auth.minChars": "Минимум",
    "auth.chars": "символов",
    "auth.invalidEmail": "Неверный формат email",
    "auth.namePlaceholder": "Иван Иванов",
    "auth.passwordPlaceholder": "Минимум 6 символов",
    
    // Notifications Toggle
    "notificationToggle.enabled": "Уведомления вкл",
    "notificationToggle.enable": "Включить уведомления",
  },
  
  uz: {
    // Greetings
    "greeting.morning": "Xayrli tong",
    "greeting.afternoon": "Xayrli kun",
    "greeting.evening": "Xayrli kech",
    
    // Settings
    "settings.title": "Sozlamalar",
    "settings.theme": "Mavzu",
    "settings.language": "Til",
    "settings.notifications": "Bildirishnomalar",
    "settings.privacy": "Maxfiylik",
    "settings.security": "Xavfsizlik",
    "settings.account": "Akkaunt",
    
    // Common
    "common.loading": "Yuklanmoqda...",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.back": "Orqaga",
    "common.next": "Keyingi",
    "common.submit": "Yuborish",
    "common.search": "Qidirish",
    "common.filter": "Filtr",
    "common.export": "Eksport",
    "common.currency": "so'm",
    "common.usd": "USD",
    "common.km": "km",
    "common.kg": "kg",
    "common.close": "Yopish",
    "common.confirm": "Tasdiqlash",
    "common.all": "Hammasi",
    "common.today": "Bugun",
    "common.yesterday": "Kecha",
    "common.week": "Hafta",
    "common.month": "Oy",
    "common.error": "Xato",
    "common.success": "Muvaffaqiyatli",
    
    // Auth
    "auth.login": "Kirish",
    "auth.logout": "Chiqish",
    "auth.register": "Ro'yxatdan o'tish",
    "auth.email": "Email",
    "auth.password": "Parol",
    "auth.forgotPassword": "Parolni unutdingizmi?",
    "auth.noAccount": "Akkauntingiz yo'qmi?",
    "auth.hasAccount": "Akkauntingiz bormi?",
    "auth.createAccount": "Akkaunt yaratish",
    
    // Navigation
    "nav.home": "Bosh sahifa",
    "nav.dashboard": "Boshqaruv paneli",
    "nav.profile": "Profil",
    "nav.orders": "Buyurtmalar",
    "nav.deals": "Bitimlar",
    "nav.settings": "Sozlamalar",
    "nav.admin": "Admin paneli",
    
    // Roles
    "role.client": "Mijoz",
    "role.carrier": "Haydovchi",
    "role.admin": "Administrator",
    "role.driver": "Haydovchi",
    "role.company": "Kompaniya",
    
    // Dashboard
    "dashboard.myDeals": "Mening bitimlarim",
    "dashboard.noDeals": "Sizda hali faol bitimlar yo'q",
    "dashboard.deals": "ta bitim",
    "dashboard.welcome": "Xush kelibsiz",
    "dashboard.subtitle.client": "Buyurtma yarating va haydovchi toping",
    "dashboard.subtitle.carrier": "Mintaqangizdagi buyurtmalarni toping",
    "dashboard.subtitle.admin": "Platformani boshqaring",
    
    // Orders
    "orders.create": "Buyurtma yaratish",
    "orders.myOrders": "Mening buyurtmalarim",
    "orders.available": "Mavjud buyurtmalar",
    "orders.cargoType": "Yuk turi",
    "orders.weight": "Og'irligi",
    "orders.dimensions": "O'lchamlari",
    "orders.pickupAddress": "Olish manzili",
    "orders.deliveryAddress": "Yetkazish manzili",
    "orders.pickupDate": "Olish sanasi",
    "orders.description": "Tavsif",
    "orders.price": "Narx",
    "orders.clientPrice": "Sizning narxingiz",
    "orders.newOrder": "Yangi buyurtma",
    "orders.fillInfo": "Yuk va marshrut haqida ma'lumot kiriting",
    "orders.selectRegion": "Mintaqani tanlang",
    "orders.selectCity": "Shaharni tanlang",
    "orders.region": "Mintaqa",
    "orders.city": "Shahar",
    "orders.cargoPhoto": "Yuk rasmi",
    "orders.comment": "Izoh",
    "orders.priceHint": "Haydovchilar sizning narxingizni ko'radi",
    "orders.status.open": "Ochiq",
    "orders.status.in_progress": "Jarayonda",
    "orders.status.completed": "Yakunlangan",
    "orders.status.cancelled": "Bekor qilingan",
    "orders.createNew": "Yangi buyurtma",
    "orders.pickupAddressFull": "To'liq olish manzili",
    
    // Carrier
    "carrier.stats": "Haydovchi statistikasi",
    "carrier.history": "Sizning tarix va yutuqlaringiz",
    "carrier.completed": "Bajarildi",
    "carrier.earned": "Topilgan",
    "carrier.rating": "Reyting",
    "carrier.inProgress": "Jarayonda",
    "carrier.completionRate": "Bajarilish darajasi",
    "carrier.ordersCompleted": "ta buyurtma bajarildi",
    "carrier.yourRating": "Sizning reytingingiz",
    "carrier.reviews": "ta sharh",
    "carrier.thisMonth": "Bu oy",
    "carrier.orders": "Buyurtmalar",
    "carrier.cancelled": "Bekor qilindi",
    "carrier.achievements": "Yutuqlar",
    "carrier.unlocked": "Ochilgan",
    "carrier.of": "dan",
    "carrier.nextAchievements": "Keyingi yutuqlar",
    "carrier.preferences": "Bildirishnoma sozlamalari",
    "carrier.respond": "Javob berish",
    "carrier.responded": "Javob berdingiz",
    "carrier.viewDetails": "Batafsil",
    "carrier.navigation": "Navigatsiya",
    "carrier.myResponses": "Mening javoblarim",
    
    // Favorites
    "favorites.title": "Sevimlilar",
    "favorites.carriers": "Sevimli haydovchilar",
    "favorites.empty": "Sizda hali sevimli haydovchilar yo'q",
    
    // Stats
    "stats.outOf": "dan",
    "level.beginner": "Yangi",
    "level.experienced": "Tajribali",
    "level.professional": "Professional",
    "level.expert": "Ekspert",
    "level.yourLevel": "Sizning darajangiz",
    "level.privileges": "Imtiyozlar",
    "level.nextLevel": "Keyingi darajagacha",
    "level.dealsNeeded": "ta buyurtma",
    "level.priorityOrders": "Ustuvor buyurtmalar",
    "level.reducedCommission": "Kamaytrilgan komissiya",
    "level.verifiedBadge": "Tasdiqlangan nishoni",
    "level.premiumSupport": "Premium yordam",
    "level.topPlacement": "Yuqori joylashuv",
    "level.exclusiveOffers": "Eksklyuziv takliflar",
    
    // Deals
    "deals.myDeals": "Mening bitimlarim",
    "deals.status.pending": "Kutilmoqda",
    "deals.status.accepted": "Qabul qilindi",
    "deals.status.in_transit": "Yo'lda",
    "deals.status.delivered": "Yetkazildi",
    "deals.status.cancelled": "Bekor qilindi",
    "deals.chat": "Chat",
    "deals.driver": "Haydovchi",
    "deals.client": "Mijoz",
    "deals.accept": "Qabul qilish",
    "deals.reject": "Rad etish",
    "deals.startDelivery": "Yetkazishni boshlash",
    "deals.completeDelivery": "Yetkazishni tugatish",
    "deals.cancel": "Bitimni bekor qilish",
    
    // Negotiation
    "negotiation.title": "Narx savdosi",
    "negotiation.clientPrice": "Mijoz narxi",
    "negotiation.currentPrice": "Joriy narx",
    "negotiation.waitingResponse": "Javob kutilmoqda",
    "negotiation.accepted": "Qabul qilindi",
    "negotiation.rejected": "Rad etildi",
    "negotiation.priceAgreed": "Narx kelishildi",
    "negotiation.proposePrice": "Narxni taklif qilish",
    "negotiation.yourPrice": "Sizning narxingiz",
    "negotiation.comment": "Izoh (ixtiyoriy)",
    "negotiation.propose": "Taklif qilish",
    
    // Chat
    "chat.writeMessage": "Xabar yozing...",
    "chat.send": "Yuborish",
    "chat.systemMessage": "Tizim xabari",
    "chat.noMessages": "Xabarlar yo'q",
    "chat.startConversation": "Suhbatni boshlang",
    
    // Calculator
    "calculator.title": "Yetkazib berish kalkulyatori",
    "calculator.description": "Markaziy Osiyo shaharlari o'rtasida narxni hisoblang",
    "calculator.from": "Qayerdan",
    "calculator.to": "Qayerga",
    "calculator.selectCity": "Shaharni tanlang",
    "calculator.cargoWeight": "Yuk og'irligi",
    "calculator.vehicleType": "Transport turi",
    "calculator.currency": "Valyuta",
    "calculator.distance": "Masofa",
    "calculator.basePrice": "Bazaviy narx",
    "calculator.distancePrice": "Masofa",
    "calculator.weightPrice": "Og'irlik",
    "calculator.vehicleSurcharge": "Transport ustamasi",
    "calculator.borderFee": "Chegara to'lovi",
    "calculator.totalPrice": "Jami",
    "calculator.internationalShipping": "Xalqaro tashish",
    "calculator.approximatePrice": "Taxminiy narx",
    "calculator.exchangeRate": "Kurs",
    
    // Map
    "map.route": "Marshrut",
    "map.showOnMap": "Xaritada ko'rsatish",
    "map.optimalRoute": "Optimal marshrut",
    "map.liveTracking": "Jonli kuzatish",
    "map.driverLocation": "Haydovchi joylashuvi",
    "map.estimatedArrival": "Taxminiy yetib kelish vaqti",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Til",
    
    // Landing Page
    "landing.hero.badge": "Markaziy Osiyo logistikasi",
    "landing.hero.title": "Yuk tashish",
    "landing.hero.titleHighlight": "yangi avlodi",
    "landing.hero.subtitle": "O'zbekiston, Qozog'iston, Qirg'iziston, Tojikiston va Turkmanistonda mijozlar, haydovchilar va logistika kompaniyalarini bog'laymiz",
    "landing.hero.cta": "Bepul boshlash",
    "landing.hero.demo": "Demoni ko'rish",
    "landing.hero.deliveries": "Yetkazmalar",
    "landing.hero.drivers": "Haydovchilar",
    "landing.hero.rating": "Reyting",
    
    "landing.features.title": "Muvaffaqiyatli logistika uchun hamma narsa",
    "landing.features.subtitle": "Barcha ishtirokchilar uchun kuchli vositalar",
    "landing.features.chat": "Aqlli chatlar",
    "landing.features.chatDesc": "Bitimdan oldin umumiy chat va har bir bitim uchun alohida chat",
    "landing.features.security": "Xavfsizlik",
    "landing.features.securityDesc": "Hujjatlarni tekshirish va himoyalangan tranzaktsiyalar",
    "landing.features.ratings": "Reytinglar",
    "landing.features.ratingsDesc": "Har bir bitimdan keyin ikki tomonlama baholar",
    "landing.features.analytics": "Tahlil",
    "landing.features.analyticsDesc": "Faoliyat grafiklari va bitim statistikasi",
    "landing.features.roles": "3 ta rol",
    "landing.features.rolesDesc": "Mijozlar, haydovchilar va kompaniyalar",
    "landing.features.fast": "Tez boshlash",
    "landing.features.fastDesc": "Ro'yxatdan o'tish 1 daqiqada, birinchi buyurtma - 5 daqiqada",
    
    "landing.roles.title": "Hamma uchun platforma",
    "landing.roles.subtitle": "Uchta foydalanuvchi turi — yagona ishonch ekotizimi",
    "landing.roles.clientDesc": "Yuk tashish kerak bo'lgan shaxs yoki biznes",
    "landing.roles.driverDesc": "Shaxsiy transportga ega mustaqil haydovchi",
    "landing.roles.companyDesc": "Haydovchilar jamoasiga ega logistika kompaniyasi",
    "landing.roles.startAs": "Sifatida boshlash",
    "landing.roles.clientF1": "Bir necha daqiqada buyurtma yaratish",
    "landing.roles.clientF2": "Haydovchi yoki kompaniyani tanlash",
    "landing.roles.clientF3": "Chat va kuzatish",
    "landing.roles.clientF4": "Ijrochilarni baholash",
    "landing.roles.driverF1": "Joriy buyurtmalarni ko'rish",
    "landing.roles.driverF2": "Moslashuvchan ish jadvali",
    "landing.roles.driverF3": "Mijoz bilan to'g'ridan-to'g'ri aloqa",
    "landing.roles.driverF4": "Reyting va daromad o'sishi",
    "landing.roles.companyF1": "Avtopark boshqaruvi",
    "landing.roles.companyF2": "Buyurtmalarni taqsimlash",
    "landing.roles.companyF3": "Tahlil va hisobotlar",
    "landing.roles.companyF4": "Yagona korporativ reyting",
    
    "landing.flow.title": "Bitim qanday ishlaydi",
    "landing.flow.subtitle": "Buyurtmadan yetkazib berishgacha oddiy va shaffof jarayon",
    "landing.flow.step": "Qadam",
    "landing.flow.order": "Buyurtma",
    "landing.flow.orderDesc": "Mijoz yuk tashish uchun buyurtma yaratadi",
    "landing.flow.response": "Javob",
    "landing.flow.responseDesc": "Haydovchi yoki kompaniya javob beradi",
    "landing.flow.negotiation": "Kelishuv",
    "landing.flow.negotiationDesc": "Chatda shartlarni muhokama qilish",
    "landing.flow.deal": "Bitim",
    "landing.flow.dealDesc": "Mijoz tasdiqlaydi — bitim chati yaratiladi",
    "landing.flow.delivery": "Yetkazib berish",
    "landing.flow.deliveryDesc": "Yuk yo'lda, status yangilanmoqda",
    "landing.flow.rating": "Baho",
    "landing.flow.ratingDesc": "Yakunlangandan keyin o'zaro baholash",
    
    "landing.trust.badge": "Ishonch tizimi",
    "landing.trust.title": "Ishonch tizimi",
    "landing.trust.subtitle": "Muvaffaqiyatli bitimlar qancha ko'p — statusingiz shuncha yuqori",
    "landing.trust.bronze": "Bronza",
    "landing.trust.bronzeReq": "Birinchi qadamlar",
    "landing.trust.silver": "Kumush",
    "landing.trust.silverReq": "Tasdiqlangan ishtirokchi",
    "landing.trust.gold": "Oltin",
    "landing.trust.goldReq": "Top ijrochi",
    "landing.trust.protection": "Soxta baholardan himoya — baholar faqat bitimlardan keyin",
    
    "landing.cta.badge": "Bepul boshlash",
    "landing.cta.title": "Boshlashga tayyormisiz?",
    "landing.cta.subtitle": "AsiaLog ga qo'shiling va yangi imkoniyatlarni oching",
    "landing.cta.create": "Akkaunt yaratish",
    "landing.cta.contact": "Biz bilan bog'laning",
    "landing.cta.free": "Bepul ro'yxatdan o'tish",
    "landing.cta.noHidden": "Yashirin to'lovlarsiz",
    
    "landing.footer.product": "Mahsulot",
    "landing.footer.company": "Kompaniya",
    "landing.footer.resources": "Resurslar",
    "landing.footer.legal": "Huquqiy ma'lumot",
    "landing.footer.features": "Imkoniyatlar",
    "landing.footer.pricing": "Narxlar",
    "landing.footer.api": "API",
    "landing.footer.about": "Biz haqimizda",
    "landing.footer.careers": "Karyera",
    "landing.footer.blog": "Blog",
    "landing.footer.docs": "Hujjatlar",
    "landing.footer.support": "Yordam",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Shartlar",
    "landing.footer.privacy": "Maxfiylik",
    "landing.footer.rights": "Barcha huquqlar himoyalangan",
    "landing.footer.description": "Markaziy Osiyo uchun logistika platformasi",
    
    // Admin Panel
    "admin.title": "Admin paneli",
    "admin.analytics": "Tahlil",
    "admin.users": "Foydalanuvchilar",
    "admin.deals": "Bitimlar",
    "admin.promos": "Promo kodlar",
    "admin.aiChat": "AI Chat",
    "admin.totalOrders": "Jami buyurtmalar",
    "admin.totalDeals": "Jami bitimlar",
    "admin.totalUsers": "Foydalanuvchilar",
    "admin.revenue": "Daromad",
    "admin.avgRating": "O'rtacha reyting",
    "admin.growth": "Haftalik o'sish",
    "admin.verified": "Tasdiqlangan",
    "admin.pending": "Tekshiruvda",
    "admin.verify": "Tasdiqlash",
    "admin.unverify": "Tasdiqlashni olib tashlash",
    "admin.newPromo": "Yangi promo kod",
    "admin.promoCode": "Kod",
    "admin.discount": "Chegirma",
    "admin.usage": "Foydalanishlar",
    "admin.active": "Faol",
    
    // Regions
    "region.uzbekistan": "O'zbekiston",
    "region.kazakhstan": "Qozog'iston",
    "region.kyrgyzstan": "Qirg'iziston",
    "region.tajikistan": "Tojikiston",
    "region.turkmenistan": "Turkmaniston",
    "region.afghanistan": "Afg'oniston",
    
    // Promo
    "promo.title": "Promo kod",
    "promo.apply": "Qo'llash",
    "promo.applied": "Promo kod qo'llandi",
    "promo.invalid": "Noto'g'ri promo kod",
    "promo.expired": "Promo kod muddati tugagan",
    "promo.alreadyUsed": "Siz bu promo kodni allaqachon ishlatgansiz",
    
    // Notifications
    "notifications.title": "Bildirishnomalar",
    "notifications.empty": "Bildirishnomalar yo'q",
    "notifications.markRead": "O'qilgan deb belgilash",
    "notifications.markAllRead": "Hammasini o'qish",
    
    // Navigation
    "navigation.title": "Navigatsiya",
    "navigation.openNavigator": "Navigatorni ochish",
    "navigation.fullNavigation": "To'liq navigatsiya",
    "navigation.buildRoute": "Marshrutni qurish",
    "navigation.followMe": "Meni kuzatish",
    "navigation.startNavigation": "Navigatsiyani boshlash",
    "navigation.stopNavigation": "To'xtatish",
    "navigation.recalculate": "Qayta hisoblash",
    "navigation.arrival": "Yetib kelish",
    "navigation.distance": "Masofa",
    "navigation.duration": "Yo'l vaqti",
    "navigation.traffic": "Tirbandlikni hisobga olish",
    "navigation.noTraffic": "Tirbandliksiz",
    "navigation.fastest": "Eng tez",
    "navigation.shortest": "Eng qisqa",
    "navigation.alternative": "Muqobil",
    "navigation.selectRoute": "Marshrutni tanlash",
    "navigation.routeDetails": "Marshrut tafsilotlari",
    "navigation.steps": "ta qadam",
    "navigation.driving": "Mashinada",
    "navigation.walking": "Piyoda",
    "navigation.voiceEnabled": "Ovoz yoqilgan",
    "navigation.voiceDisabled": "Ovoz o'chirilgan",
    "navigation.offlineMode": "Oflayn rejim",
    "navigation.downloadMap": "Xaritani yuklab olish",
    "navigation.mapDownloaded": "Xarita yuklandi",
    "navigation.cacheRoute": "Marshrutni keshlash",
    "navigation.speedCamera": "Tezlik nazorati kamerasi",
    "navigation.speedLimit": "Tezlik chegarasi",
    "navigation.ahead": "oldinda",
    "navigation.meters": "m",
    "navigation.km": "km",
    "navigation.hours": "soat",
    "navigation.minutes": "daq",
    "navigation.yourSpeed": "Sizning tezligingiz",
    "navigation.heading": "Yo'nalish",
    
    // Deal Chat
    "dealChat.title": "Bitim chati",
    "dealChat.error": "Xato",
    "dealChat.dealNotFound": "Bitim topilmadi",
    "dealChat.accessDenied": "Kirish taqiqlangan",
    "dealChat.notParticipant": "Siz bu bitim ishtirokchisi emassiz",
    "dealChat.statusUpdated": "Status yangilandi",
    "dealChat.updateFailed": "Statusni yangilab bo'lmadi",
    "dealChat.acceptOrder": "Buyurtmani qabul qilish",
    "dealChat.carrierAccepted": "Haydovchi buyurtmani qabul qildi",
    "dealChat.startDelivery": "Yetkazishni boshlash",
    "dealChat.cargoInTransit": "Yuk yo'lda",
    "dealChat.completeDelivery": "Yetkazishni tugatish",
    "dealChat.cargoDelivered": "Yuk yetkazildi!",
    "dealChat.cancelDeal": "Bitimni bekor qilish",
    "dealChat.cancelQuestion": "Bitimni bekor qilasizmi?",
    "dealChat.cancelDescription": "Bitim bekor qilinadi va buyurtma boshqa haydovchilar uchun mavjud bo'ladi. Ikkinchi tomon bekor qilish haqida xabar oladi.",
    "dealChat.cancelReason": "Bekor qilish sababi",
    "dealChat.cancelReasonPlaceholder": "Bitimni bekor qilish sababini ko'rsating...",
    "dealChat.dealCancelled": "Bitim bekor qilindi",
    "dealChat.orderAvailable": "Buyurtma endi boshqa haydovchilar uchun mavjud",
    "dealChat.cancelFailed": "Bitimni bekor qilib bo'lmadi",
    "dealChat.cancelling": "Bekor qilinmoqda...",
    "dealChat.participant": "Ishtirokchi",
    "dealChat.priceUpdated": "Narx yangilandi",
    "dealChat.newAgreedPrice": "Yangi kelishilgan narx",
    "dealChat.yourReview": "Sizning sharhingiz",
    "dealChat.reviewFrom": "dan sharh",
    "dealChat.carrier": "Haydovchi",
    "dealChat.client": "Mijoz",
    
    // Errors
    "error.generic": "Xatolik yuz berdi",
    "error.tryAgain": "Qaytadan urinib ko'ring",
    "error.notFound": "Topilmadi",
    "error.unauthorized": "Kirish taqiqlangan",
    "error.networkError": "Tarmoq xatosi",
    "error.serverError": "Server xatosi",
    
    // Success
    "success.saved": "Saqlandi",
    "success.updated": "Yangilandi",
    "success.deleted": "O'chirildi",
    "success.created": "Yaratildi",
    
    // Confirmation
    "confirm.areYouSure": "Ishonchingiz komilmi?",
    "confirm.thisCannotBeUndone": "Bu amalni ortga qaytarib bo'lmaydi.",
    "confirm.yes": "Ha",
    "confirm.no": "Yo'q",
    
    // Profile
    "profile.title": "Profil",
    "profile.myProfile": "Mening profilim",
    "profile.userProfile": "Foydalanuvchi profili",
    "profile.editProfile": "Profilni tahrirlash",
    "profile.updateInfo": "O'zingiz haqida ma'lumotni yangilang",
    "profile.clickToUpload": "Rasm yuklash uchun bosing",
    "profile.name": "Ism",
    "profile.phone": "Telefon",
    "profile.companyName": "Kompaniya nomi",
    "profile.vehicleType": "Transport turi",
    "profile.saving": "Saqlanmoqda...",
    "profile.avatarUpdated": "Avatar yangilandi",
    "profile.newPhotoSaved": "Yangi profil rasmi saqlandi",
    "profile.uploadError": "Yuklash xatosi",
    "profile.uploadFailed": "Rasmni yuklab bo'lmadi",
    "profile.profileUpdated": "Profil yangilandi",
    "profile.changesSaved": "O'zgarishlar muvaffaqiyatli saqlandi",
    "profile.saveFailed": "O'zgarishlarni saqlab bo'lmadi",
    "profile.wrongFormat": "Noto'g'ri format",
    "profile.selectImage": "Iltimos, rasm tanlang",
    "profile.fileTooLarge": "Fayl juda katta",
    "profile.maxFileSize": "Maksimal fayl hajmi — 5 MB",
    "profile.notFound": "Profil topilmadi",
    "profile.noName": "Ismsiz",
    "profile.verified": "Tasdiqlangan",
    "profile.onPlatformSince": "Platformada",
    "profile.company": "Kompaniya",
    "profile.vehicle": "Transport",
    "profile.totalDeals": "Jami bitimlar",
    "profile.completed": "Yakunlangan",
    "profile.active": "Faol",
    "profile.rating": "Reyting",
    "profile.ratingDistribution": "Baholar taqsimoti",
    "profile.reviews": "Sharhlar",
    "profile.verification": "Tasdiqlash",
    "profile.noReviewsYet": "Foydalanuvchida hali sharhlar yo'q",
    "profile.reviewsCount": "ta sharh",
    "profile.review": "ta sharh",
    "profile.user": "Foydalanuvchi",
    
    // Orders List
    "ordersList.myOrders": "Mening buyurtmalarim",
    "ordersList.totalOrders": "Jami buyurtmalar",
    "ordersList.noOrdersYet": "Sizda hali buyurtmalar yo'q",
    "ordersList.createFirstOrder": "Yuqorida birinchi buyurtmani yarating",
    "ordersList.loadingOrders": "Buyurtmalar yuklanmoqda...",
    "ordersList.responses": "ta javob",
    "ordersList.photos": "ta rasm",
    "ordersList.canEdit": "O'zgartirish mumkin",
    "ordersList.details": "Batafsil",
    "ordersList.cancelOrder": "Bekor qilish",
    "ordersList.cancelOrderTitle": "Buyurtmani bekor qilasizmi?",
    "ordersList.cancelOrderDesc": "Siz ushbu buyurtmani bekor qilmoqchimisiz? Bu amalni ortga qaytarib bo'lmaydi. Barcha haydovchi javoblari rad etiladi.",
    "ordersList.dontCancel": "Bekor qilmang",
    "ordersList.yesCancel": "Ha, bekor qiling",
    "ordersList.orderCancelled": "Buyurtma bekor qilindi",
    "ordersList.orderCancelledDesc": "Buyurtmangiz muvaffaqiyatli bekor qilindi",
    "ordersList.cancelFailed": "Buyurtmani bekor qilib bo'lmadi",
    
    // AI Chat
    "aiChat.title": "AI Yordamchi",
    "aiChat.subtitle": "Haydovchi tanlash va hisob-kitob",
    "aiChat.clearChat": "Chatni tozalash",
    "aiChat.greeting": "Salom! Men haydovchi tanlash va yetkazib berish narxini hisoblashda yordam beraman.",
    "aiChat.historySaved": "Tarix avtomatik saqlanadi",
    "aiChat.askQuestion": "Savol bering...",
    "aiChat.rateResponse": "Javobni baholang:",
    "aiChat.quickQuestion1": "Narxni qanday hisoblash mumkin?",
    "aiChat.quickQuestion2": "Qaysi haydovchi yaxshiroq?",
    "aiChat.quickQuestion3": "Shoshilinch yetkazib berish qancha turadi?",
    
    // Auth Page
    "auth.backToHome": "Bosh sahifaga",
    "auth.platformName": "LogiFlow",
    "auth.platformDesc": "Yuk tashish platformasi",
    "auth.loginTab": "Kirish",
    "auth.registerTab": "Ro'yxatdan o'tish",
    "auth.loggingIn": "Kirilmoqda...",
    "auth.registering": "Ro'yxatdan o'tilmoqda...",
    "auth.selectRole": "Rolni tanlang",
    "auth.iOrderDelivery": "Yuk tashish buyurtma qilaman",
    "auth.iExecuteOrders": "Buyurtmalarni bajaraman",
    "auth.referralCode": "Referal kod (ixtiyoriy)",
    "auth.enterFriendCode": "Do'stingiz kodini kiriting",
    "auth.codeValid": "Kod to'g'ri",
    "auth.codeNotFound": "Kod topilmadi",
    "auth.registerAs": "Sifatida ro'yxatdan o'tish",
    "auth.orFullRegistration": "yoki",
    "auth.fullRegistration": "to'liq ro'yxatdan o'tish →",
    "auth.validationError": "Tekshirish xatosi",
    "auth.loginError": "Kirish xatosi",
    "auth.loginFailed": "Kirishda xatolik yuz berdi",
    "auth.invalidCredentials": "Noto'g'ri email yoki parol",
    "auth.emailNotConfirmed": "Email tasdiqlanmagan",
    "auth.welcome": "Xush kelibsiz!",
    "auth.loginSuccess": "Siz muvaffaqiyatli kirdingiz",
    "auth.registrationError": "Ro'yxatdan o'tish xatosi",
    "auth.registrationFailed": "Ro'yxatdan o'tishda xatolik yuz berdi",
    "auth.emailAlreadyRegistered": "Bu email allaqachon ro'yxatdan o'tgan",
    "auth.registrationSuccess": "Ro'yxatdan o'tish muvaffaqiyatli!",
    "auth.welcomeToPlatform": "LogiFlow'ga xush kelibsiz",
    "auth.minChars": "Kamida",
    "auth.chars": "ta belgi",
    "auth.invalidEmail": "Noto'g'ri email formati",
    "auth.namePlaceholder": "Ism Familiya",
    "auth.passwordPlaceholder": "Kamida 6 ta belgi",
    
    // Notifications Toggle
    "notificationToggle.enabled": "Bildirishnomalar yoqilgan",
    "notificationToggle.enable": "Bildirishnomalarni yoqish",
  },
  
  en: {
    // Greetings
    "greeting.morning": "Good morning",
    "greeting.afternoon": "Good afternoon",
    "greeting.evening": "Good evening",
    
    // Settings
    "settings.title": "Settings",
    "settings.theme": "Theme",
    "settings.language": "Language",
    "settings.notifications": "Notifications",
    "settings.privacy": "Privacy",
    "settings.security": "Security",
    "settings.account": "Account",
    
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.currency": "UZS",
    "common.usd": "USD",
    "common.km": "km",
    "common.kg": "kg",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.all": "All",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.week": "Week",
    "common.month": "Month",
    "common.error": "Error",
    "common.success": "Success",
    
    // Auth
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.createAccount": "Create Account",
    
    // Navigation
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.orders": "Orders",
    "nav.deals": "Deals",
    "nav.settings": "Settings",
    "nav.admin": "Admin Panel",
    
    // Roles
    "role.client": "Client",
    "role.carrier": "Carrier",
    "role.admin": "Administrator",
    "role.driver": "Driver",
    "role.company": "Company",
    
    // Dashboard
    "dashboard.myDeals": "My Deals",
    "dashboard.noDeals": "You don't have any active deals yet",
    "dashboard.deals": "deals",
    "dashboard.welcome": "Welcome",
    "dashboard.subtitle.client": "Create an order and find a carrier",
    "dashboard.subtitle.carrier": "Find orders in your region",
    "dashboard.subtitle.admin": "Manage the platform",
    
    // Orders
    "orders.create": "Create Order",
    "orders.myOrders": "My Orders",
    "orders.available": "Available Orders",
    "orders.cargoType": "Cargo Type",
    "orders.weight": "Weight",
    "orders.dimensions": "Dimensions",
    "orders.pickupAddress": "Pickup Address",
    "orders.deliveryAddress": "Delivery Address",
    "orders.pickupDate": "Pickup Date",
    "orders.description": "Description",
    "orders.price": "Price",
    "orders.clientPrice": "Your Price",
    "orders.newOrder": "New Order",
    "orders.fillInfo": "Fill in cargo and route information",
    "orders.selectRegion": "Select region",
    "orders.selectCity": "Select city",
    "orders.region": "Region",
    "orders.city": "City",
    "orders.cargoPhoto": "Cargo Photo",
    "orders.comment": "Comment",
    "orders.priceHint": "Carriers will see your price",
    "orders.status.open": "Open",
    "orders.status.in_progress": "In Progress",
    "orders.status.completed": "Completed",
    "orders.status.cancelled": "Cancelled",
    "orders.createNew": "New Order",
    "orders.pickupAddressFull": "Full pickup address",
    
    // Carrier
    "carrier.stats": "Carrier Statistics",
    "carrier.history": "Your history and achievements",
    "carrier.completed": "Completed",
    "carrier.earned": "Earned",
    "carrier.rating": "Rating",
    "carrier.inProgress": "In Progress",
    "carrier.completionRate": "Completion Rate",
    "carrier.ordersCompleted": "orders completed",
    "carrier.yourRating": "Your Rating",
    "carrier.reviews": "reviews",
    "carrier.thisMonth": "This Month",
    "carrier.orders": "Orders",
    "carrier.cancelled": "Cancelled",
    "carrier.achievements": "Achievements",
    "carrier.unlocked": "Unlocked",
    "carrier.of": "of",
    "carrier.nextAchievements": "Next Achievements",
    "carrier.preferences": "Notification Settings",
    "carrier.respond": "Respond",
    "carrier.responded": "You responded",
    "carrier.viewDetails": "Details",
    "carrier.navigation": "Navigation",
    "carrier.myResponses": "My Responses",
    
    // Favorites
    "favorites.title": "Favorites",
    "favorites.carriers": "Favorite Carriers",
    "favorites.empty": "You don't have any favorite carriers yet",
    
    // Stats
    "stats.outOf": "of",
    "level.beginner": "Beginner",
    "level.experienced": "Experienced",
    "level.professional": "Professional",
    "level.expert": "Expert",
    "level.yourLevel": "Your Level",
    "level.privileges": "Privileges",
    "level.nextLevel": "To Next Level",
    "level.dealsNeeded": "deals",
    "level.priorityOrders": "Priority Orders",
    "level.reducedCommission": "Reduced Commission",
    "level.verifiedBadge": "Verified Badge",
    "level.premiumSupport": "Premium Support",
    "level.topPlacement": "Top Placement",
    "level.exclusiveOffers": "Exclusive Offers",
    
    // Deals
    "deals.myDeals": "My Deals",
    "deals.status.pending": "Pending",
    "deals.status.accepted": "Accepted",
    "deals.status.in_transit": "In Transit",
    "deals.status.delivered": "Delivered",
    "deals.status.cancelled": "Cancelled",
    "deals.chat": "Chat",
    "deals.driver": "Driver",
    "deals.client": "Client",
    "deals.accept": "Accept",
    "deals.reject": "Reject",
    "deals.startDelivery": "Start Delivery",
    "deals.completeDelivery": "Complete Delivery",
    "deals.cancel": "Cancel Deal",
    
    // Negotiation
    "negotiation.title": "Price Negotiation",
    "negotiation.clientPrice": "Client Price",
    "negotiation.currentPrice": "Current Price",
    "negotiation.waitingResponse": "Waiting Response",
    "negotiation.accepted": "Accepted",
    "negotiation.rejected": "Rejected",
    "negotiation.priceAgreed": "Price Agreed",
    "negotiation.proposePrice": "Propose Price",
    "negotiation.yourPrice": "Your Price",
    "negotiation.comment": "Comment (optional)",
    "negotiation.propose": "Propose",
    
    // Chat
    "chat.writeMessage": "Write a message...",
    "chat.send": "Send",
    "chat.systemMessage": "System message",
    "chat.noMessages": "No messages",
    "chat.startConversation": "Start a conversation",
    
    // Calculator
    "calculator.title": "Delivery Calculator",
    "calculator.description": "Calculate cost between Central Asian cities",
    "calculator.from": "From",
    "calculator.to": "To",
    "calculator.selectCity": "Select city",
    "calculator.cargoWeight": "Cargo Weight",
    "calculator.vehicleType": "Vehicle Type",
    "calculator.currency": "Currency",
    "calculator.distance": "Distance",
    "calculator.basePrice": "Base Price",
    "calculator.distancePrice": "Distance",
    "calculator.weightPrice": "Weight",
    "calculator.vehicleSurcharge": "Vehicle Surcharge",
    "calculator.borderFee": "Border Fee",
    "calculator.totalPrice": "Total",
    "calculator.internationalShipping": "International Shipping",
    "calculator.approximatePrice": "Approximate Price",
    "calculator.exchangeRate": "Exchange Rate",
    
    // Map
    "map.route": "Route",
    "map.showOnMap": "Show on Map",
    "map.optimalRoute": "Optimal Route",
    "map.liveTracking": "Live Tracking",
    "map.driverLocation": "Driver Location",
    "map.estimatedArrival": "Estimated Arrival",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Language",
    
    // Landing Page
    "landing.hero.badge": "Central Asia Logistics",
    "landing.hero.title": "Freight Transport",
    "landing.hero.titleHighlight": "Next Generation",
    "landing.hero.subtitle": "Connecting clients, drivers and logistics companies in Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan",
    "landing.hero.cta": "Get Started Free",
    "landing.hero.demo": "Watch Demo",
    "landing.hero.deliveries": "Deliveries",
    "landing.hero.drivers": "Drivers",
    "landing.hero.rating": "Rating",
    
    "landing.features.title": "Everything for Successful Logistics",
    "landing.features.subtitle": "Powerful tools for all participants",
    "landing.features.chat": "Smart Chats",
    "landing.features.chatDesc": "General chat before deal and separate chat for each deal",
    "landing.features.security": "Security",
    "landing.features.securityDesc": "Document verification and secure transactions",
    "landing.features.ratings": "Ratings",
    "landing.features.ratingsDesc": "Two-way ratings after each deal",
    "landing.features.analytics": "Analytics",
    "landing.features.analyticsDesc": "Activity charts and deal statistics",
    "landing.features.roles": "3 Roles",
    "landing.features.rolesDesc": "Clients, drivers and companies",
    "landing.features.fast": "Quick Start",
    "landing.features.fastDesc": "Registration in 1 minute, first order in 5 minutes",
    
    "landing.roles.title": "Platform for Everyone",
    "landing.roles.subtitle": "Three user types — one trust ecosystem",
    "landing.roles.clientDesc": "Person or business that needs cargo transport",
    "landing.roles.driverDesc": "Independent driver with personal transport",
    "landing.roles.companyDesc": "Logistics company with driver team",
    "landing.roles.startAs": "Start as",
    "landing.roles.clientF1": "Create orders in minutes",
    "landing.roles.clientF2": "Choose driver or company",
    "landing.roles.clientF3": "Chat and tracking",
    "landing.roles.clientF4": "Rate performers",
    "landing.roles.driverF1": "View current orders",
    "landing.roles.driverF2": "Flexible work schedule",
    "landing.roles.driverF3": "Direct contact with client",
    "landing.roles.driverF4": "Rating and income growth",
    "landing.roles.companyF1": "Fleet management",
    "landing.roles.companyF2": "Order distribution",
    "landing.roles.companyF3": "Analytics and reports",
    "landing.roles.companyF4": "Single corporate rating",
    
    "landing.flow.title": "How a Deal Works",
    "landing.flow.subtitle": "Simple and transparent process from order to delivery",
    "landing.flow.step": "Step",
    "landing.flow.order": "Order",
    "landing.flow.orderDesc": "Client creates a transport order",
    "landing.flow.response": "Response",
    "landing.flow.responseDesc": "Driver or company responds",
    "landing.flow.negotiation": "Negotiation",
    "landing.flow.negotiationDesc": "Discuss terms in chat",
    "landing.flow.deal": "Deal",
    "landing.flow.dealDesc": "Client confirms — deal chat is created",
    "landing.flow.delivery": "Delivery",
    "landing.flow.deliveryDesc": "Cargo in transit, status updating",
    "landing.flow.rating": "Rating",
    "landing.flow.ratingDesc": "Mutual ratings after completion",
    
    "landing.trust.badge": "Trust System",
    "landing.trust.title": "Trust System",
    "landing.trust.subtitle": "More successful deals — higher your status",
    "landing.trust.bronze": "Bronze",
    "landing.trust.bronzeReq": "First steps",
    "landing.trust.silver": "Silver",
    "landing.trust.silverReq": "Verified participant",
    "landing.trust.gold": "Gold",
    "landing.trust.goldReq": "Top performer",
    "landing.trust.protection": "Fake rating protection — ratings only after deals",
    
    "landing.cta.badge": "Free Start",
    "landing.cta.title": "Ready to Start?",
    "landing.cta.subtitle": "Join AsiaLog and unlock new opportunities",
    "landing.cta.create": "Create Account",
    "landing.cta.contact": "Contact Us",
    "landing.cta.free": "Free registration",
    "landing.cta.noHidden": "No hidden fees",
    
    "landing.footer.product": "Product",
    "landing.footer.company": "Company",
    "landing.footer.resources": "Resources",
    "landing.footer.legal": "Legal",
    "landing.footer.features": "Features",
    "landing.footer.pricing": "Pricing",
    "landing.footer.api": "API",
    "landing.footer.about": "About Us",
    "landing.footer.careers": "Careers",
    "landing.footer.blog": "Blog",
    "landing.footer.docs": "Documentation",
    "landing.footer.support": "Support",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Terms",
    "landing.footer.privacy": "Privacy",
    "landing.footer.rights": "All rights reserved",
    "landing.footer.description": "Logistics platform for Central Asia",
    
    // Admin Panel
    "admin.title": "Admin Panel",
    "admin.analytics": "Analytics",
    "admin.users": "Users",
    "admin.deals": "Deals",
    "admin.promos": "Promo Codes",
    "admin.aiChat": "AI Chat",
    "admin.totalOrders": "Total Orders",
    "admin.totalDeals": "Total Deals",
    "admin.totalUsers": "Users",
    "admin.revenue": "Revenue",
    "admin.avgRating": "Average Rating",
    "admin.growth": "Weekly Growth",
    "admin.verified": "Verified",
    "admin.pending": "Pending Review",
    "admin.verify": "Verify",
    "admin.unverify": "Remove Verification",
    "admin.newPromo": "New Promo Code",
    "admin.promoCode": "Code",
    "admin.discount": "Discount",
    "admin.usage": "Usage",
    "admin.active": "Active",
    
    // Regions
    "region.uzbekistan": "Uzbekistan",
    "region.kazakhstan": "Kazakhstan",
    "region.kyrgyzstan": "Kyrgyzstan",
    "region.tajikistan": "Tajikistan",
    "region.turkmenistan": "Turkmenistan",
    "region.afghanistan": "Afghanistan",
    
    // Promo
    "promo.title": "Promo Code",
    "promo.apply": "Apply",
    "promo.applied": "Promo code applied",
    "promo.invalid": "Invalid promo code",
    "promo.expired": "Promo code expired",
    "promo.alreadyUsed": "You have already used this promo code",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.empty": "No notifications",
    "notifications.markRead": "Mark as read",
    "notifications.markAllRead": "Mark all as read",
    
    // Navigation
    "navigation.title": "Navigation",
    "navigation.openNavigator": "Open Navigator",
    "navigation.fullNavigation": "Full Navigation",
    "navigation.buildRoute": "Build Route",
    "navigation.followMe": "Follow Me",
    "navigation.startNavigation": "Start Navigation",
    "navigation.stopNavigation": "Stop",
    "navigation.recalculate": "Recalculate",
    "navigation.arrival": "Arrival",
    "navigation.distance": "Distance",
    "navigation.duration": "Duration",
    "navigation.traffic": "With Traffic",
    "navigation.noTraffic": "Without Traffic",
    "navigation.fastest": "Fastest",
    "navigation.shortest": "Shortest",
    "navigation.alternative": "Alternative",
    "navigation.selectRoute": "Select Route",
    "navigation.routeDetails": "Route Details",
    "navigation.steps": "steps",
    "navigation.driving": "Driving",
    "navigation.walking": "Walking",
    "navigation.voiceEnabled": "Voice Enabled",
    "navigation.voiceDisabled": "Voice Disabled",
    "navigation.offlineMode": "Offline Mode",
    "navigation.downloadMap": "Download Map",
    "navigation.mapDownloaded": "Map Downloaded",
    "navigation.cacheRoute": "Cache Route",
    "navigation.speedCamera": "Speed Camera",
    "navigation.speedLimit": "Speed Limit",
    "navigation.ahead": "ahead",
    "navigation.meters": "m",
    "navigation.km": "km",
    "navigation.hours": "h",
    "navigation.minutes": "min",
    "navigation.yourSpeed": "Your Speed",
    "navigation.heading": "Heading",
    
    // Deal Chat
    "dealChat.title": "Deal Chat",
    "dealChat.error": "Error",
    "dealChat.dealNotFound": "Deal not found",
    "dealChat.accessDenied": "Access denied",
    "dealChat.notParticipant": "You are not a participant of this deal",
    "dealChat.statusUpdated": "Status updated",
    "dealChat.updateFailed": "Failed to update status",
    "dealChat.acceptOrder": "Accept Order",
    "dealChat.carrierAccepted": "Carrier accepted the order",
    "dealChat.startDelivery": "Start Delivery",
    "dealChat.cargoInTransit": "Cargo in transit",
    "dealChat.completeDelivery": "Complete Delivery",
    "dealChat.cargoDelivered": "Cargo delivered!",
    "dealChat.cancelDeal": "Cancel Deal",
    "dealChat.cancelQuestion": "Cancel this deal?",
    "dealChat.cancelDescription": "The deal will be cancelled and the order will be available for other carriers. The other party will be notified.",
    "dealChat.cancelReason": "Cancellation reason",
    "dealChat.cancelReasonPlaceholder": "Specify the reason for cancellation...",
    "dealChat.dealCancelled": "Deal cancelled",
    "dealChat.orderAvailable": "Order is now available for other carriers",
    "dealChat.cancelFailed": "Failed to cancel deal",
    "dealChat.cancelling": "Cancelling...",
    "dealChat.participant": "Participant",
    "dealChat.priceUpdated": "Price updated",
    "dealChat.newAgreedPrice": "New agreed price",
    "dealChat.yourReview": "Your review",
    "dealChat.reviewFrom": "Review from",
    "dealChat.carrier": "Carrier",
    "dealChat.client": "Client",
    
    // Errors
    "error.generic": "An error occurred",
    "error.tryAgain": "Try again",
    "error.notFound": "Not found",
    "error.unauthorized": "Unauthorized",
    "error.networkError": "Network error",
    "error.serverError": "Server error",
    
    // Success
    "success.saved": "Saved",
    "success.updated": "Updated",
    "success.deleted": "Deleted",
    "success.created": "Created",
    
    // Confirmation
    "confirm.areYouSure": "Are you sure?",
    "confirm.thisCannotBeUndone": "This action cannot be undone.",
    "confirm.yes": "Yes",
    "confirm.no": "No",
    
    // Profile
    "profile.title": "Profile",
    "profile.myProfile": "My Profile",
    "profile.userProfile": "User Profile",
    "profile.editProfile": "Edit Profile",
    "profile.updateInfo": "Update your information",
    "profile.clickToUpload": "Click to upload photo",
    "profile.name": "Name",
    "profile.phone": "Phone",
    "profile.companyName": "Company Name",
    "profile.vehicleType": "Vehicle Type",
    "profile.saving": "Saving...",
    "profile.avatarUpdated": "Avatar updated",
    "profile.newPhotoSaved": "New profile photo saved",
    "profile.uploadError": "Upload error",
    "profile.uploadFailed": "Failed to upload image",
    "profile.profileUpdated": "Profile updated",
    "profile.changesSaved": "Changes saved successfully",
    "profile.saveFailed": "Failed to save changes",
    "profile.wrongFormat": "Wrong format",
    "profile.selectImage": "Please select an image",
    "profile.fileTooLarge": "File too large",
    "profile.maxFileSize": "Maximum file size is 5 MB",
    "profile.notFound": "Profile not found",
    "profile.noName": "No name",
    "profile.verified": "Verified",
    "profile.onPlatformSince": "On platform since",
    "profile.company": "Company",
    "profile.vehicle": "Vehicle",
    "profile.totalDeals": "Total Deals",
    "profile.completed": "Completed",
    "profile.active": "Active",
    "profile.rating": "Rating",
    "profile.ratingDistribution": "Rating Distribution",
    "profile.reviews": "Reviews",
    "profile.verification": "Verification",
    "profile.noReviewsYet": "User has no reviews yet",
    "profile.reviewsCount": "reviews",
    "profile.review": "review",
    "profile.user": "User",
    
    // Orders List
    "ordersList.myOrders": "My Orders",
    "ordersList.totalOrders": "Total orders",
    "ordersList.noOrdersYet": "You don't have any orders yet",
    "ordersList.createFirstOrder": "Create your first order above",
    "ordersList.loadingOrders": "Loading orders...",
    "ordersList.responses": "responses",
    "ordersList.photos": "photos",
    "ordersList.canEdit": "Can edit",
    "ordersList.details": "Details",
    "ordersList.cancelOrder": "Cancel",
    "ordersList.cancelOrderTitle": "Cancel order?",
    "ordersList.cancelOrderDesc": "Are you sure you want to cancel this order? This action cannot be undone. All carrier responses will be rejected.",
    "ordersList.dontCancel": "Don't cancel",
    "ordersList.yesCancel": "Yes, cancel",
    "ordersList.orderCancelled": "Order cancelled",
    "ordersList.orderCancelledDesc": "Your order has been successfully cancelled",
    "ordersList.cancelFailed": "Failed to cancel order",
    
    // AI Chat
    "aiChat.title": "AI Assistant",
    "aiChat.subtitle": "Carrier selection and price calculation",
    "aiChat.clearChat": "Clear chat",
    "aiChat.greeting": "Hello! I'll help you choose a carrier and calculate delivery cost.",
    "aiChat.historySaved": "History is saved automatically",
    "aiChat.askQuestion": "Ask a question...",
    "aiChat.rateResponse": "Rate this response:",
    "aiChat.quickQuestion1": "How to calculate the cost?",
    "aiChat.quickQuestion2": "Which carrier is better?",
    "aiChat.quickQuestion3": "How much is urgent delivery?",
    
    // Auth Page
    "auth.backToHome": "Back to Home",
    "auth.platformName": "LogiFlow",
    "auth.platformDesc": "Freight transport platform",
    "auth.loginTab": "Login",
    "auth.registerTab": "Register",
    "auth.loggingIn": "Logging in...",
    "auth.registering": "Registering...",
    "auth.selectRole": "Select role",
    "auth.iOrderDelivery": "I order deliveries",
    "auth.iExecuteOrders": "I execute orders",
    "auth.referralCode": "Referral code (optional)",
    "auth.enterFriendCode": "Enter friend's code",
    "auth.codeValid": "Code is valid",
    "auth.codeNotFound": "Code not found",
    "auth.registerAs": "Register as",
    "auth.orFullRegistration": "or",
    "auth.fullRegistration": "complete full registration →",
    "auth.validationError": "Validation error",
    "auth.loginError": "Login error",
    "auth.loginFailed": "An error occurred during login",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.emailNotConfirmed": "Email not confirmed",
    "auth.welcome": "Welcome!",
    "auth.loginSuccess": "You have successfully logged in",
    "auth.registrationError": "Registration error",
    "auth.registrationFailed": "An error occurred during registration",
    "auth.emailAlreadyRegistered": "This email is already registered",
    "auth.registrationSuccess": "Registration successful!",
    "auth.welcomeToPlatform": "Welcome to LogiFlow",
    "auth.minChars": "Minimum",
    "auth.chars": "characters",
    "auth.invalidEmail": "Invalid email format",
    "auth.namePlaceholder": "John Doe",
    "auth.passwordPlaceholder": "Minimum 6 characters",
    
    // Notifications Toggle
    "notificationToggle.enabled": "Notifications on",
    "notificationToggle.enable": "Enable notifications",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "ru";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
