import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ru" | "uz" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Extended Translations
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Common
    "common.loading": "Загрузка...",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Редактировать",
    "common.back": "Назад",
    "common.next": "Далее",
    "common.submit": "Отправить",
    "common.search": "Поиск",
    "common.filter": "Фильтр",
    "common.export": "Экспорт",
    "common.currency": "сўм",
    "common.usd": "USD",
    "common.km": "км",
    "common.kg": "кг",
    "common.close": "Закрыть",
    "common.confirm": "Подтвердить",
    "common.all": "Все",
    "common.today": "Сегодня",
    "common.yesterday": "Вчера",
    "common.week": "Неделя",
    "common.month": "Месяц",
    
    // Auth
    "auth.login": "Войти",
    "auth.logout": "Выйти",
    "auth.register": "Регистрация",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.forgotPassword": "Забыли пароль?",
    "auth.noAccount": "Нет аккаунта?",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.createAccount": "Создать аккаунт",
    
    // Navigation
    "nav.home": "Главная",
    "nav.dashboard": "Панель управления",
    "nav.profile": "Профиль",
    "nav.orders": "Заказы",
    "nav.deals": "Сделки",
    "nav.settings": "Настройки",
    "nav.admin": "Админ-панель",
    
    // Roles
    "role.client": "Клиент",
    "role.carrier": "Перевозчик",
    "role.admin": "Администратор",
    "role.driver": "Водитель",
    "role.company": "Компания",
    
    // Dashboard
    "dashboard.myDeals": "Мои сделки",
    "dashboard.noDeals": "У вас пока нет активных сделок",
    "dashboard.deals": "сделок",
    "dashboard.welcome": "Добро пожаловать",
    "dashboard.subtitle.client": "Создайте заявку и найдите перевозчика",
    "dashboard.subtitle.carrier": "Найдите заказы в вашем регионе",
    "dashboard.subtitle.admin": "Управляйте платформой",
    
    // Orders
    "orders.create": "Создать заявку",
    "orders.myOrders": "Мои заявки",
    "orders.available": "Доступные заказы",
    "orders.cargoType": "Тип груза",
    "orders.weight": "Вес",
    "orders.dimensions": "Габариты",
    "orders.pickupAddress": "Адрес погрузки",
    "orders.deliveryAddress": "Адрес доставки",
    "orders.pickupDate": "Дата погрузки",
    "orders.description": "Описание",
    "orders.price": "Цена",
    "orders.clientPrice": "Ваша цена",
    "orders.newOrder": "Новая заявка",
    "orders.fillInfo": "Заполните информацию о грузе и маршруте",
    "orders.selectRegion": "Выберите регион",
    "orders.selectCity": "Выберите город",
    "orders.region": "Регион",
    "orders.city": "Город",
    "orders.cargoPhoto": "Фото груза",
    "orders.comment": "Комментарий",
    "orders.priceHint": "Перевозчики увидят вашу цену",
    "orders.status.open": "Открыта",
    "orders.status.in_progress": "В работе",
    "orders.status.completed": "Завершена",
    "orders.status.cancelled": "Отменена",
    
    // Carrier
    "carrier.stats": "Статистика перевозчика",
    "carrier.history": "Ваша история и достижения",
    "carrier.completed": "Выполнено",
    "carrier.earned": "Заработано",
    "carrier.rating": "Рейтинг",
    "carrier.inProgress": "В работе",
    "carrier.completionRate": "Завершённость",
    "carrier.ordersCompleted": "заказов выполнено",
    "carrier.yourRating": "Ваш рейтинг",
    "carrier.reviews": "отзывов",
    "carrier.thisMonth": "В этом месяце",
    "carrier.orders": "Заказов",
    "carrier.cancelled": "Отменено",
    "carrier.achievements": "Достижения",
    "carrier.unlocked": "Разблокировано",
    "carrier.of": "из",
    "carrier.nextAchievements": "Следующие достижения",
    "carrier.preferences": "Настройки уведомлений",
    "carrier.respond": "Откликнуться",
    "carrier.responded": "Вы откликнулись",
    "carrier.viewDetails": "Подробнее",
    
    // Levels
    "level.beginner": "Новичок",
    "level.experienced": "Опытный",
    "level.professional": "Профессионал",
    "level.expert": "Эксперт",
    "level.yourLevel": "Ваш уровень",
    "level.privileges": "Привилегии",
    "level.nextLevel": "До следующего уровня",
    "level.dealsNeeded": "заказов",
    "level.priorityOrders": "Приоритетные заказы",
    "level.reducedCommission": "Сниженная комиссия",
    "level.verifiedBadge": "Значок проверенного",
    "level.premiumSupport": "Премиум поддержка",
    "level.topPlacement": "Топ размещение",
    "level.exclusiveOffers": "Эксклюзивные предложения",
    
    // Deals
    "deals.status.pending": "Ожидает",
    "deals.status.accepted": "Принята",
    "deals.status.in_transit": "В пути",
    "deals.status.delivered": "Доставлено",
    "deals.status.cancelled": "Отменена",
    "deals.chat": "Чат",
    "deals.driver": "Перевозчик",
    "deals.client": "Клиент",
    "deals.accept": "Принять",
    "deals.reject": "Отклонить",
    "deals.startDelivery": "Начать доставку",
    "deals.completeDelivery": "Завершить доставку",
    "deals.cancel": "Отменить сделку",
    
    // Negotiation
    "negotiation.title": "Торг по цене",
    "negotiation.clientPrice": "Цена клиента",
    "negotiation.currentPrice": "Текущая цена",
    "negotiation.waitingResponse": "Ожидает ответа",
    "negotiation.accepted": "Принято",
    "negotiation.rejected": "Отклонено",
    "negotiation.priceAgreed": "Цена согласована",
    "negotiation.proposePrice": "Предложить цену",
    "negotiation.yourPrice": "Ваша цена",
    "negotiation.comment": "Комментарий (необязательно)",
    "negotiation.propose": "Предложить",
    
    // Chat
    "chat.writeMessage": "Напишите сообщение...",
    "chat.send": "Отправить",
    "chat.systemMessage": "Системное сообщение",
    "chat.noMessages": "Нет сообщений",
    "chat.startConversation": "Начните диалог",
    
    // Calculator
    "calculator.title": "Калькулятор доставки",
    "calculator.description": "Рассчитайте стоимость между городами Центральной Азии",
    "calculator.from": "Откуда",
    "calculator.to": "Куда",
    "calculator.selectCity": "Выберите город",
    "calculator.cargoWeight": "Вес груза",
    "calculator.vehicleType": "Тип транспорта",
    "calculator.currency": "Валюта",
    "calculator.distance": "Расстояние",
    "calculator.basePrice": "Базовая цена",
    "calculator.distancePrice": "Расстояние",
    "calculator.weightPrice": "Вес",
    "calculator.vehicleSurcharge": "Надбавка транспорта",
    "calculator.borderFee": "Пошлина границы",
    "calculator.totalPrice": "Итого",
    "calculator.internationalShipping": "Международная перевозка",
    "calculator.approximatePrice": "Примерная цена",
    "calculator.exchangeRate": "Курс",
    
    // Map
    "map.route": "Маршрут",
    "map.showOnMap": "Показать на карте",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Язык",
    
    // Landing Page
    "landing.hero.badge": "Логистика Центральной Азии",
    "landing.hero.title": "Грузоперевозки",
    "landing.hero.titleHighlight": "нового поколения",
    "landing.hero.subtitle": "Соединяем клиентов, водителей и логистические компании в Узбекистане, Казахстане, Кыргызстане, Таджикистане и Туркменистане",
    "landing.hero.cta": "Начать бесплатно",
    "landing.hero.demo": "Смотреть демо",
    "landing.hero.deliveries": "Перевозок",
    "landing.hero.drivers": "Водителей",
    "landing.hero.rating": "Рейтинг",
    
    "landing.features.title": "Всё для успешной логистики",
    "landing.features.subtitle": "Мощные инструменты для всех участников процесса",
    "landing.features.chat": "Умные чаты",
    "landing.features.chatDesc": "Общий чат до сделки и отдельный чат для каждой сделки",
    "landing.features.security": "Безопасность",
    "landing.features.securityDesc": "Верификация документов и защищённые транзакции",
    "landing.features.ratings": "Рейтинги",
    "landing.features.ratingsDesc": "Двусторонние оценки после каждой сделки",
    "landing.features.analytics": "Аналитика",
    "landing.features.analyticsDesc": "Графики активности и статистика сделок",
    "landing.features.roles": "3 роли",
    "landing.features.rolesDesc": "Клиенты, водители и компании",
    "landing.features.fast": "Быстрый старт",
    "landing.features.fastDesc": "Регистрация за минуту, первая заявка — за 5 минут",
    
    "landing.roles.title": "Платформа для каждого",
    "landing.roles.subtitle": "Три типа пользователей — единая экосистема доверия",
    "landing.roles.clientDesc": "Человек или бизнес, которому нужно перевезти груз",
    "landing.roles.driverDesc": "Независимый водитель с личным транспортом",
    "landing.roles.companyDesc": "Логистическая компания с командой водителей",
    "landing.roles.startAs": "Начать как",
    "landing.roles.clientF1": "Создание заявок за минуты",
    "landing.roles.clientF2": "Выбор водителя или компании",
    "landing.roles.clientF3": "Чат и отслеживание",
    "landing.roles.clientF4": "Оценка исполнителей",
    "landing.roles.driverF1": "Просмотр актуальных заявок",
    "landing.roles.driverF2": "Гибкий график работы",
    "landing.roles.driverF3": "Прямая связь с клиентом",
    "landing.roles.driverF4": "Рост рейтинга и дохода",
    "landing.roles.companyF1": "Управление автопарком",
    "landing.roles.companyF2": "Распределение заказов",
    "landing.roles.companyF3": "Аналитика и отчёты",
    "landing.roles.companyF4": "Единый корпоративный рейтинг",
    
    "landing.flow.title": "Как работает сделка",
    "landing.flow.subtitle": "Простой и прозрачный процесс от заявки до доставки",
    "landing.flow.step": "Шаг",
    "landing.flow.order": "Заявка",
    "landing.flow.orderDesc": "Клиент создаёт заявку на перевозку",
    "landing.flow.response": "Отклик",
    "landing.flow.responseDesc": "Водитель или компания откликается",
    "landing.flow.negotiation": "Согласование",
    "landing.flow.negotiationDesc": "Обсуждение условий в чате",
    "landing.flow.deal": "Сделка",
    "landing.flow.dealDesc": "Клиент подтверждает — создаётся чат сделки",
    "landing.flow.delivery": "Доставка",
    "landing.flow.deliveryDesc": "Груз в пути с обновлением статуса",
    "landing.flow.rating": "Оценка",
    "landing.flow.ratingDesc": "Взаимные оценки после завершения",
    
    "landing.trust.badge": "Система доверия",
    "landing.trust.title": "Система доверия",
    "landing.trust.subtitle": "Чем больше успешных сделок — тем выше ваш статус",
    "landing.trust.bronze": "Бронза",
    "landing.trust.bronzeReq": "Первые шаги",
    "landing.trust.silver": "Серебро",
    "landing.trust.silverReq": "Проверенный участник",
    "landing.trust.gold": "Золото",
    "landing.trust.goldReq": "Топ исполнитель",
    "landing.trust.protection": "Защита от накруток — оценки только после сделок",
    
    "landing.cta.badge": "Бесплатный старт",
    "landing.cta.title": "Готовы начать?",
    "landing.cta.subtitle": "Присоединяйтесь к AsiaLog и откройте новые возможности",
    "landing.cta.create": "Создать аккаунт",
    "landing.cta.contact": "Связаться с нами",
    "landing.cta.free": "Бесплатная регистрация",
    "landing.cta.noHidden": "Без скрытых платежей",
    
    "landing.footer.product": "Продукт",
    "landing.footer.company": "Компания",
    "landing.footer.resources": "Ресурсы",
    "landing.footer.legal": "Правовая информация",
    "landing.footer.features": "Возможности",
    "landing.footer.pricing": "Тарифы",
    "landing.footer.api": "API",
    "landing.footer.about": "О нас",
    "landing.footer.careers": "Карьера",
    "landing.footer.blog": "Блог",
    "landing.footer.docs": "Документация",
    "landing.footer.support": "Поддержка",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Условия",
    "landing.footer.privacy": "Конфиденциальность",
    "landing.footer.rights": "Все права защищены",
    "landing.footer.description": "Логистическая платформа для Центральной Азии",
    
    // Admin Panel
    "admin.title": "Админ-панель",
    "admin.analytics": "Аналитика",
    "admin.users": "Пользователи",
    "admin.deals": "Сделки",
    "admin.promos": "Промокоды",
    "admin.aiChat": "AI Чат",
    "admin.totalOrders": "Всего заказов",
    "admin.totalDeals": "Всего сделок",
    "admin.totalUsers": "Пользователей",
    "admin.revenue": "Выручка",
    "admin.avgRating": "Средний рейтинг",
    "admin.growth": "Рост за неделю",
    "admin.verified": "Верифицировано",
    "admin.pending": "На проверке",
    "admin.verify": "Верифицировать",
    "admin.unverify": "Снять верификацию",
    "admin.newPromo": "Новый промокод",
    "admin.promoCode": "Код",
    "admin.discount": "Скидка",
    "admin.usage": "Использований",
    "admin.active": "Активен",
    
    // Regions
    "region.uzbekistan": "Узбекистан",
    "region.kazakhstan": "Казахстан",
    "region.kyrgyzstan": "Кыргызстан",
    "region.tajikistan": "Таджикистан",
    "region.turkmenistan": "Туркменистан",
    "region.afghanistan": "Афганистан",
    
    // Promo
    "promo.title": "Промокод",
    "promo.apply": "Применить",
    "promo.applied": "Промокод применён",
    "promo.invalid": "Недействительный промокод",
    "promo.expired": "Промокод истёк",
    "promo.alreadyUsed": "Вы уже использовали этот промокод",
    
    // Notifications
    "notifications.title": "Уведомления",
    "notifications.empty": "Нет уведомлений",
    "notifications.markRead": "Отметить прочитанным",
    "notifications.markAllRead": "Прочитать все",
  },
  
  uz: {
    // Common
    "common.loading": "Yuklanmoqda...",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.back": "Orqaga",
    "common.next": "Keyingi",
    "common.submit": "Yuborish",
    "common.search": "Qidirish",
    "common.filter": "Filtr",
    "common.export": "Eksport",
    "common.currency": "so'm",
    "common.usd": "USD",
    "common.km": "km",
    "common.kg": "kg",
    "common.close": "Yopish",
    "common.confirm": "Tasdiqlash",
    "common.all": "Hammasi",
    "common.today": "Bugun",
    "common.yesterday": "Kecha",
    "common.week": "Hafta",
    "common.month": "Oy",
    
    // Auth
    "auth.login": "Kirish",
    "auth.logout": "Chiqish",
    "auth.register": "Ro'yxatdan o'tish",
    "auth.email": "Email",
    "auth.password": "Parol",
    "auth.forgotPassword": "Parolni unutdingizmi?",
    "auth.noAccount": "Akkauntingiz yo'qmi?",
    "auth.hasAccount": "Akkauntingiz bormi?",
    "auth.createAccount": "Akkaunt yaratish",
    
    // Navigation
    "nav.home": "Bosh sahifa",
    "nav.dashboard": "Boshqaruv paneli",
    "nav.profile": "Profil",
    "nav.orders": "Buyurtmalar",
    "nav.deals": "Bitimlar",
    "nav.settings": "Sozlamalar",
    "nav.admin": "Admin paneli",
    
    // Roles
    "role.client": "Mijoz",
    "role.carrier": "Haydovchi",
    "role.admin": "Administrator",
    "role.driver": "Haydovchi",
    "role.company": "Kompaniya",
    
    // Dashboard
    "dashboard.myDeals": "Mening bitimlarim",
    "dashboard.noDeals": "Sizda hali faol bitimlar yo'q",
    "dashboard.deals": "ta bitim",
    "dashboard.welcome": "Xush kelibsiz",
    "dashboard.subtitle.client": "Buyurtma yarating va haydovchi toping",
    "dashboard.subtitle.carrier": "Mintaqangizdagi buyurtmalarni toping",
    "dashboard.subtitle.admin": "Platformani boshqaring",
    
    // Orders
    "orders.create": "Buyurtma yaratish",
    "orders.myOrders": "Mening buyurtmalarim",
    "orders.available": "Mavjud buyurtmalar",
    "orders.cargoType": "Yuk turi",
    "orders.weight": "Og'irligi",
    "orders.dimensions": "O'lchamlari",
    "orders.pickupAddress": "Olish manzili",
    "orders.deliveryAddress": "Yetkazish manzili",
    "orders.pickupDate": "Olish sanasi",
    "orders.description": "Tavsif",
    "orders.price": "Narx",
    "orders.clientPrice": "Sizning narxingiz",
    "orders.newOrder": "Yangi buyurtma",
    "orders.fillInfo": "Yuk va marshrut haqida ma'lumot kiriting",
    "orders.selectRegion": "Mintaqani tanlang",
    "orders.selectCity": "Shaharni tanlang",
    "orders.region": "Mintaqa",
    "orders.city": "Shahar",
    "orders.cargoPhoto": "Yuk rasmi",
    "orders.comment": "Izoh",
    "orders.priceHint": "Haydovchilar sizning narxingizni ko'radi",
    "orders.status.open": "Ochiq",
    "orders.status.in_progress": "Jarayonda",
    "orders.status.completed": "Yakunlangan",
    "orders.status.cancelled": "Bekor qilingan",
    
    // Carrier
    "carrier.stats": "Haydovchi statistikasi",
    "carrier.history": "Sizning tarix va yutuqlaringiz",
    "carrier.completed": "Bajarildi",
    "carrier.earned": "Topilgan",
    "carrier.rating": "Reyting",
    "carrier.inProgress": "Jarayonda",
    "carrier.completionRate": "Bajarilish darajasi",
    "carrier.ordersCompleted": "ta buyurtma bajarildi",
    "carrier.yourRating": "Sizning reytingingiz",
    "carrier.reviews": "ta sharh",
    "carrier.thisMonth": "Bu oy",
    "carrier.orders": "Buyurtmalar",
    "carrier.cancelled": "Bekor qilindi",
    "carrier.achievements": "Yutuqlar",
    "carrier.unlocked": "Ochilgan",
    "carrier.of": "dan",
    "carrier.nextAchievements": "Keyingi yutuqlar",
    "carrier.preferences": "Bildirishnoma sozlamalari",
    "carrier.respond": "Javob berish",
    "carrier.responded": "Javob berdingiz",
    "carrier.viewDetails": "Batafsil",
    
    // Levels
    "level.beginner": "Yangi",
    "level.experienced": "Tajribali",
    "level.professional": "Professional",
    "level.expert": "Ekspert",
    "level.yourLevel": "Sizning darajangiz",
    "level.privileges": "Imtiyozlar",
    "level.nextLevel": "Keyingi darajagacha",
    "level.dealsNeeded": "ta buyurtma",
    "level.priorityOrders": "Ustuvor buyurtmalar",
    "level.reducedCommission": "Kamaytrilgan komissiya",
    "level.verifiedBadge": "Tasdiqlangan nishoni",
    "level.premiumSupport": "Premium yordam",
    "level.topPlacement": "Yuqori joylashuv",
    "level.exclusiveOffers": "Eksklyuziv takliflar",
    
    // Deals
    "deals.status.pending": "Kutilmoqda",
    "deals.status.accepted": "Qabul qilindi",
    "deals.status.in_transit": "Yo'lda",
    "deals.status.delivered": "Yetkazildi",
    "deals.status.cancelled": "Bekor qilindi",
    "deals.chat": "Chat",
    "deals.driver": "Haydovchi",
    "deals.client": "Mijoz",
    "deals.accept": "Qabul qilish",
    "deals.reject": "Rad etish",
    "deals.startDelivery": "Yetkazishni boshlash",
    "deals.completeDelivery": "Yetkazishni tugatish",
    "deals.cancel": "Bitimni bekor qilish",
    
    // Negotiation
    "negotiation.title": "Narx savdosi",
    "negotiation.clientPrice": "Mijoz narxi",
    "negotiation.currentPrice": "Joriy narx",
    "negotiation.waitingResponse": "Javob kutilmoqda",
    "negotiation.accepted": "Qabul qilindi",
    "negotiation.rejected": "Rad etildi",
    "negotiation.priceAgreed": "Narx kelishildi",
    "negotiation.proposePrice": "Narxni taklif qilish",
    "negotiation.yourPrice": "Sizning narxingiz",
    "negotiation.comment": "Izoh (ixtiyoriy)",
    "negotiation.propose": "Taklif qilish",
    
    // Chat
    "chat.writeMessage": "Xabar yozing...",
    "chat.send": "Yuborish",
    "chat.systemMessage": "Tizim xabari",
    "chat.noMessages": "Xabarlar yo'q",
    "chat.startConversation": "Suhbatni boshlang",
    
    // Calculator
    "calculator.title": "Yetkazib berish kalkulyatori",
    "calculator.description": "Markaziy Osiyo shaharlari o'rtasida narxni hisoblang",
    "calculator.from": "Qayerdan",
    "calculator.to": "Qayerga",
    "calculator.selectCity": "Shaharni tanlang",
    "calculator.cargoWeight": "Yuk og'irligi",
    "calculator.vehicleType": "Transport turi",
    "calculator.currency": "Valyuta",
    "calculator.distance": "Masofa",
    "calculator.basePrice": "Bazaviy narx",
    "calculator.distancePrice": "Masofa",
    "calculator.weightPrice": "Og'irlik",
    "calculator.vehicleSurcharge": "Transport ustamasi",
    "calculator.borderFee": "Chegara to'lovi",
    "calculator.totalPrice": "Jami",
    "calculator.internationalShipping": "Xalqaro tashish",
    "calculator.approximatePrice": "Taxminiy narx",
    "calculator.exchangeRate": "Kurs",
    
    // Map
    "map.route": "Marshrut",
    "map.showOnMap": "Xaritada ko'rsatish",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Til",
    
    // Landing Page
    "landing.hero.badge": "Markaziy Osiyo logistikasi",
    "landing.hero.title": "Yuk tashish",
    "landing.hero.titleHighlight": "yangi avlodi",
    "landing.hero.subtitle": "O'zbekiston, Qozog'iston, Qirg'iziston, Tojikiston va Turkmanistonda mijozlar, haydovchilar va logistika kompaniyalarini bog'laymiz",
    "landing.hero.cta": "Bepul boshlash",
    "landing.hero.demo": "Demoni ko'rish",
    "landing.hero.deliveries": "Yetkazmalar",
    "landing.hero.drivers": "Haydovchilar",
    "landing.hero.rating": "Reyting",
    
    "landing.features.title": "Muvaffaqiyatli logistika uchun hamma narsa",
    "landing.features.subtitle": "Barcha ishtirokchilar uchun kuchli vositalar",
    "landing.features.chat": "Aqlli chatlar",
    "landing.features.chatDesc": "Bitimdan oldin umumiy chat va har bir bitim uchun alohida chat",
    "landing.features.security": "Xavfsizlik",
    "landing.features.securityDesc": "Hujjatlarni tekshirish va himoyalangan tranzaktsiyalar",
    "landing.features.ratings": "Reytinglar",
    "landing.features.ratingsDesc": "Har bir bitimdan keyin ikki tomonlama baholar",
    "landing.features.analytics": "Tahlil",
    "landing.features.analyticsDesc": "Faoliyat grafiklari va bitim statistikasi",
    "landing.features.roles": "3 ta rol",
    "landing.features.rolesDesc": "Mijozlar, haydovchilar va kompaniyalar",
    "landing.features.fast": "Tez boshlash",
    "landing.features.fastDesc": "Ro'yxatdan o'tish 1 daqiqada, birinchi buyurtma - 5 daqiqada",
    
    "landing.roles.title": "Hamma uchun platforma",
    "landing.roles.subtitle": "Uchta foydalanuvchi turi — yagona ishonch ekotizimi",
    "landing.roles.clientDesc": "Yuk tashish kerak bo'lgan shaxs yoki biznes",
    "landing.roles.driverDesc": "Shaxsiy transportga ega mustaqil haydovchi",
    "landing.roles.companyDesc": "Haydovchilar jamoasiga ega logistika kompaniyasi",
    "landing.roles.startAs": "Sifatida boshlash",
    "landing.roles.clientF1": "Bir necha daqiqada buyurtma yaratish",
    "landing.roles.clientF2": "Haydovchi yoki kompaniyani tanlash",
    "landing.roles.clientF3": "Chat va kuzatish",
    "landing.roles.clientF4": "Ijrochilarni baholash",
    "landing.roles.driverF1": "Joriy buyurtmalarni ko'rish",
    "landing.roles.driverF2": "Moslashuvchan ish jadvali",
    "landing.roles.driverF3": "Mijoz bilan to'g'ridan-to'g'ri aloqa",
    "landing.roles.driverF4": "Reyting va daromad o'sishi",
    "landing.roles.companyF1": "Avtopark boshqaruvi",
    "landing.roles.companyF2": "Buyurtmalarni taqsimlash",
    "landing.roles.companyF3": "Tahlil va hisobotlar",
    "landing.roles.companyF4": "Yagona korporativ reyting",
    
    "landing.flow.title": "Bitim qanday ishlaydi",
    "landing.flow.subtitle": "Buyurtmadan yetkazib berishgacha oddiy va shaffof jarayon",
    "landing.flow.step": "Qadam",
    "landing.flow.order": "Buyurtma",
    "landing.flow.orderDesc": "Mijoz yuk tashish uchun buyurtma yaratadi",
    "landing.flow.response": "Javob",
    "landing.flow.responseDesc": "Haydovchi yoki kompaniya javob beradi",
    "landing.flow.negotiation": "Kelishuv",
    "landing.flow.negotiationDesc": "Chatda shartlarni muhokama qilish",
    "landing.flow.deal": "Bitim",
    "landing.flow.dealDesc": "Mijoz tasdiqlaydi — bitim chati yaratiladi",
    "landing.flow.delivery": "Yetkazib berish",
    "landing.flow.deliveryDesc": "Yuk yo'lda, status yangilanmoqda",
    "landing.flow.rating": "Baho",
    "landing.flow.ratingDesc": "Yakunlangandan keyin o'zaro baholash",
    
    "landing.trust.badge": "Ishonch tizimi",
    "landing.trust.title": "Ishonch tizimi",
    "landing.trust.subtitle": "Muvaffaqiyatli bitimlar qancha ko'p — statusingiz shuncha yuqori",
    "landing.trust.bronze": "Bronza",
    "landing.trust.bronzeReq": "Birinchi qadamlar",
    "landing.trust.silver": "Kumush",
    "landing.trust.silverReq": "Tasdiqlangan ishtirokchi",
    "landing.trust.gold": "Oltin",
    "landing.trust.goldReq": "Top ijrochi",
    "landing.trust.protection": "Soxta baholardan himoya — baholar faqat bitimlardan keyin",
    
    "landing.cta.badge": "Bepul boshlash",
    "landing.cta.title": "Boshlashga tayyormisiz?",
    "landing.cta.subtitle": "AsiaLog ga qo'shiling va yangi imkoniyatlarni oching",
    "landing.cta.create": "Akkaunt yaratish",
    "landing.cta.contact": "Biz bilan bog'laning",
    "landing.cta.free": "Bepul ro'yxatdan o'tish",
    "landing.cta.noHidden": "Yashirin to'lovlarsiz",
    
    "landing.footer.product": "Mahsulot",
    "landing.footer.company": "Kompaniya",
    "landing.footer.resources": "Resurslar",
    "landing.footer.legal": "Huquqiy ma'lumot",
    "landing.footer.features": "Imkoniyatlar",
    "landing.footer.pricing": "Narxlar",
    "landing.footer.api": "API",
    "landing.footer.about": "Biz haqimizda",
    "landing.footer.careers": "Karyera",
    "landing.footer.blog": "Blog",
    "landing.footer.docs": "Hujjatlar",
    "landing.footer.support": "Yordam",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Shartlar",
    "landing.footer.privacy": "Maxfiylik",
    "landing.footer.rights": "Barcha huquqlar himoyalangan",
    "landing.footer.description": "Markaziy Osiyo uchun logistika platformasi",
    
    // Admin Panel
    "admin.title": "Admin paneli",
    "admin.analytics": "Tahlil",
    "admin.users": "Foydalanuvchilar",
    "admin.deals": "Bitimlar",
    "admin.promos": "Promo kodlar",
    "admin.aiChat": "AI Chat",
    "admin.totalOrders": "Jami buyurtmalar",
    "admin.totalDeals": "Jami bitimlar",
    "admin.totalUsers": "Foydalanuvchilar",
    "admin.revenue": "Daromad",
    "admin.avgRating": "O'rtacha reyting",
    "admin.growth": "Haftalik o'sish",
    "admin.verified": "Tasdiqlangan",
    "admin.pending": "Tekshiruvda",
    "admin.verify": "Tasdiqlash",
    "admin.unverify": "Tasdiqlashni olib tashlash",
    "admin.newPromo": "Yangi promo kod",
    "admin.promoCode": "Kod",
    "admin.discount": "Chegirma",
    "admin.usage": "Foydalanishlar",
    "admin.active": "Faol",
    
    // Regions
    "region.uzbekistan": "O'zbekiston",
    "region.kazakhstan": "Qozog'iston",
    "region.kyrgyzstan": "Qirg'iziston",
    "region.tajikistan": "Tojikiston",
    "region.turkmenistan": "Turkmaniston",
    "region.afghanistan": "Afg'oniston",
    
    // Promo
    "promo.title": "Promo kod",
    "promo.apply": "Qo'llash",
    "promo.applied": "Promo kod qo'llandi",
    "promo.invalid": "Noto'g'ri promo kod",
    "promo.expired": "Promo kod muddati tugagan",
    "promo.alreadyUsed": "Siz bu promo kodni allaqachon ishlatgansiz",
    
    // Notifications
    "notifications.title": "Bildirishnomalar",
    "notifications.empty": "Bildirishnomalar yo'q",
    "notifications.markRead": "O'qilgan deb belgilash",
    "notifications.markAllRead": "Hammasini o'qish",
  },
  
  en: {
    // Common
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.submit": "Submit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.currency": "UZS",
    "common.usd": "USD",
    "common.km": "km",
    "common.kg": "kg",
    "common.close": "Close",
    "common.confirm": "Confirm",
    "common.all": "All",
    "common.today": "Today",
    "common.yesterday": "Yesterday",
    "common.week": "Week",
    "common.month": "Month",
    
    // Auth
    "auth.login": "Login",
    "auth.logout": "Logout",
    "auth.register": "Register",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.createAccount": "Create Account",
    
    // Navigation
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.profile": "Profile",
    "nav.orders": "Orders",
    "nav.deals": "Deals",
    "nav.settings": "Settings",
    "nav.admin": "Admin Panel",
    
    // Roles
    "role.client": "Client",
    "role.carrier": "Carrier",
    "role.admin": "Administrator",
    "role.driver": "Driver",
    "role.company": "Company",
    
    // Dashboard
    "dashboard.myDeals": "My Deals",
    "dashboard.noDeals": "You don't have any active deals yet",
    "dashboard.deals": "deals",
    "dashboard.welcome": "Welcome",
    "dashboard.subtitle.client": "Create an order and find a carrier",
    "dashboard.subtitle.carrier": "Find orders in your region",
    "dashboard.subtitle.admin": "Manage the platform",
    
    // Orders
    "orders.create": "Create Order",
    "orders.myOrders": "My Orders",
    "orders.available": "Available Orders",
    "orders.cargoType": "Cargo Type",
    "orders.weight": "Weight",
    "orders.dimensions": "Dimensions",
    "orders.pickupAddress": "Pickup Address",
    "orders.deliveryAddress": "Delivery Address",
    "orders.pickupDate": "Pickup Date",
    "orders.description": "Description",
    "orders.price": "Price",
    "orders.clientPrice": "Your Price",
    "orders.newOrder": "New Order",
    "orders.fillInfo": "Fill in cargo and route information",
    "orders.selectRegion": "Select region",
    "orders.selectCity": "Select city",
    "orders.region": "Region",
    "orders.city": "City",
    "orders.cargoPhoto": "Cargo Photo",
    "orders.comment": "Comment",
    "orders.priceHint": "Carriers will see your price",
    "orders.status.open": "Open",
    "orders.status.in_progress": "In Progress",
    "orders.status.completed": "Completed",
    "orders.status.cancelled": "Cancelled",
    
    // Carrier
    "carrier.stats": "Carrier Statistics",
    "carrier.history": "Your history and achievements",
    "carrier.completed": "Completed",
    "carrier.earned": "Earned",
    "carrier.rating": "Rating",
    "carrier.inProgress": "In Progress",
    "carrier.completionRate": "Completion Rate",
    "carrier.ordersCompleted": "orders completed",
    "carrier.yourRating": "Your Rating",
    "carrier.reviews": "reviews",
    "carrier.thisMonth": "This Month",
    "carrier.orders": "Orders",
    "carrier.cancelled": "Cancelled",
    "carrier.achievements": "Achievements",
    "carrier.unlocked": "Unlocked",
    "carrier.of": "of",
    "carrier.nextAchievements": "Next Achievements",
    "carrier.preferences": "Notification Settings",
    "carrier.respond": "Respond",
    "carrier.responded": "You responded",
    "carrier.viewDetails": "Details",
    
    // Levels
    "level.beginner": "Beginner",
    "level.experienced": "Experienced",
    "level.professional": "Professional",
    "level.expert": "Expert",
    "level.yourLevel": "Your Level",
    "level.privileges": "Privileges",
    "level.nextLevel": "To Next Level",
    "level.dealsNeeded": "deals",
    "level.priorityOrders": "Priority Orders",
    "level.reducedCommission": "Reduced Commission",
    "level.verifiedBadge": "Verified Badge",
    "level.premiumSupport": "Premium Support",
    "level.topPlacement": "Top Placement",
    "level.exclusiveOffers": "Exclusive Offers",
    
    // Deals
    "deals.status.pending": "Pending",
    "deals.status.accepted": "Accepted",
    "deals.status.in_transit": "In Transit",
    "deals.status.delivered": "Delivered",
    "deals.status.cancelled": "Cancelled",
    "deals.chat": "Chat",
    "deals.driver": "Driver",
    "deals.client": "Client",
    "deals.accept": "Accept",
    "deals.reject": "Reject",
    "deals.startDelivery": "Start Delivery",
    "deals.completeDelivery": "Complete Delivery",
    "deals.cancel": "Cancel Deal",
    
    // Negotiation
    "negotiation.title": "Price Negotiation",
    "negotiation.clientPrice": "Client Price",
    "negotiation.currentPrice": "Current Price",
    "negotiation.waitingResponse": "Waiting Response",
    "negotiation.accepted": "Accepted",
    "negotiation.rejected": "Rejected",
    "negotiation.priceAgreed": "Price Agreed",
    "negotiation.proposePrice": "Propose Price",
    "negotiation.yourPrice": "Your Price",
    "negotiation.comment": "Comment (optional)",
    "negotiation.propose": "Propose",
    
    // Chat
    "chat.writeMessage": "Write a message...",
    "chat.send": "Send",
    "chat.systemMessage": "System message",
    "chat.noMessages": "No messages",
    "chat.startConversation": "Start a conversation",
    
    // Calculator
    "calculator.title": "Delivery Calculator",
    "calculator.description": "Calculate cost between Central Asian cities",
    "calculator.from": "From",
    "calculator.to": "To",
    "calculator.selectCity": "Select city",
    "calculator.cargoWeight": "Cargo Weight",
    "calculator.vehicleType": "Vehicle Type",
    "calculator.currency": "Currency",
    "calculator.distance": "Distance",
    "calculator.basePrice": "Base Price",
    "calculator.distancePrice": "Distance",
    "calculator.weightPrice": "Weight",
    "calculator.vehicleSurcharge": "Vehicle Surcharge",
    "calculator.borderFee": "Border Fee",
    "calculator.totalPrice": "Total",
    "calculator.internationalShipping": "International Shipping",
    "calculator.approximatePrice": "Approximate Price",
    "calculator.exchangeRate": "Exchange Rate",
    
    // Map
    "map.route": "Route",
    "map.showOnMap": "Show on Map",
    
    // Languages
    "language.ru": "Русский",
    "language.uz": "O'zbek",
    "language.en": "English",
    "language.select": "Language",
    
    // Landing Page
    "landing.hero.badge": "Central Asia Logistics",
    "landing.hero.title": "Freight Transport",
    "landing.hero.titleHighlight": "Next Generation",
    "landing.hero.subtitle": "Connecting clients, drivers and logistics companies in Uzbekistan, Kazakhstan, Kyrgyzstan, Tajikistan and Turkmenistan",
    "landing.hero.cta": "Get Started Free",
    "landing.hero.demo": "Watch Demo",
    "landing.hero.deliveries": "Deliveries",
    "landing.hero.drivers": "Drivers",
    "landing.hero.rating": "Rating",
    
    "landing.features.title": "Everything for Successful Logistics",
    "landing.features.subtitle": "Powerful tools for all participants",
    "landing.features.chat": "Smart Chats",
    "landing.features.chatDesc": "General chat before deal and separate chat for each deal",
    "landing.features.security": "Security",
    "landing.features.securityDesc": "Document verification and secure transactions",
    "landing.features.ratings": "Ratings",
    "landing.features.ratingsDesc": "Two-way ratings after each deal",
    "landing.features.analytics": "Analytics",
    "landing.features.analyticsDesc": "Activity charts and deal statistics",
    "landing.features.roles": "3 Roles",
    "landing.features.rolesDesc": "Clients, drivers and companies",
    "landing.features.fast": "Quick Start",
    "landing.features.fastDesc": "Registration in 1 minute, first order in 5 minutes",
    
    "landing.roles.title": "Platform for Everyone",
    "landing.roles.subtitle": "Three user types — one trust ecosystem",
    "landing.roles.clientDesc": "Person or business that needs cargo transport",
    "landing.roles.driverDesc": "Independent driver with personal transport",
    "landing.roles.companyDesc": "Logistics company with driver team",
    "landing.roles.startAs": "Start as",
    "landing.roles.clientF1": "Create orders in minutes",
    "landing.roles.clientF2": "Choose driver or company",
    "landing.roles.clientF3": "Chat and tracking",
    "landing.roles.clientF4": "Rate performers",
    "landing.roles.driverF1": "View current orders",
    "landing.roles.driverF2": "Flexible work schedule",
    "landing.roles.driverF3": "Direct contact with client",
    "landing.roles.driverF4": "Rating and income growth",
    "landing.roles.companyF1": "Fleet management",
    "landing.roles.companyF2": "Order distribution",
    "landing.roles.companyF3": "Analytics and reports",
    "landing.roles.companyF4": "Single corporate rating",
    
    "landing.flow.title": "How a Deal Works",
    "landing.flow.subtitle": "Simple and transparent process from order to delivery",
    "landing.flow.step": "Step",
    "landing.flow.order": "Order",
    "landing.flow.orderDesc": "Client creates a transport order",
    "landing.flow.response": "Response",
    "landing.flow.responseDesc": "Driver or company responds",
    "landing.flow.negotiation": "Negotiation",
    "landing.flow.negotiationDesc": "Discuss terms in chat",
    "landing.flow.deal": "Deal",
    "landing.flow.dealDesc": "Client confirms — deal chat is created",
    "landing.flow.delivery": "Delivery",
    "landing.flow.deliveryDesc": "Cargo in transit, status updating",
    "landing.flow.rating": "Rating",
    "landing.flow.ratingDesc": "Mutual ratings after completion",
    
    "landing.trust.badge": "Trust System",
    "landing.trust.title": "Trust System",
    "landing.trust.subtitle": "More successful deals — higher your status",
    "landing.trust.bronze": "Bronze",
    "landing.trust.bronzeReq": "First steps",
    "landing.trust.silver": "Silver",
    "landing.trust.silverReq": "Verified participant",
    "landing.trust.gold": "Gold",
    "landing.trust.goldReq": "Top performer",
    "landing.trust.protection": "Fake rating protection — ratings only after deals",
    
    "landing.cta.badge": "Free Start",
    "landing.cta.title": "Ready to Start?",
    "landing.cta.subtitle": "Join AsiaLog and unlock new opportunities",
    "landing.cta.create": "Create Account",
    "landing.cta.contact": "Contact Us",
    "landing.cta.free": "Free registration",
    "landing.cta.noHidden": "No hidden fees",
    
    "landing.footer.product": "Product",
    "landing.footer.company": "Company",
    "landing.footer.resources": "Resources",
    "landing.footer.legal": "Legal",
    "landing.footer.features": "Features",
    "landing.footer.pricing": "Pricing",
    "landing.footer.api": "API",
    "landing.footer.about": "About Us",
    "landing.footer.careers": "Careers",
    "landing.footer.blog": "Blog",
    "landing.footer.docs": "Documentation",
    "landing.footer.support": "Support",
    "landing.footer.faq": "FAQ",
    "landing.footer.terms": "Terms",
    "landing.footer.privacy": "Privacy",
    "landing.footer.rights": "All rights reserved",
    "landing.footer.description": "Logistics platform for Central Asia",
    
    // Admin Panel
    "admin.title": "Admin Panel",
    "admin.analytics": "Analytics",
    "admin.users": "Users",
    "admin.deals": "Deals",
    "admin.promos": "Promo Codes",
    "admin.aiChat": "AI Chat",
    "admin.totalOrders": "Total Orders",
    "admin.totalDeals": "Total Deals",
    "admin.totalUsers": "Users",
    "admin.revenue": "Revenue",
    "admin.avgRating": "Average Rating",
    "admin.growth": "Weekly Growth",
    "admin.verified": "Verified",
    "admin.pending": "Pending Review",
    "admin.verify": "Verify",
    "admin.unverify": "Remove Verification",
    "admin.newPromo": "New Promo Code",
    "admin.promoCode": "Code",
    "admin.discount": "Discount",
    "admin.usage": "Usage",
    "admin.active": "Active",
    
    // Regions
    "region.uzbekistan": "Uzbekistan",
    "region.kazakhstan": "Kazakhstan",
    "region.kyrgyzstan": "Kyrgyzstan",
    "region.tajikistan": "Tajikistan",
    "region.turkmenistan": "Turkmenistan",
    "region.afghanistan": "Afghanistan",
    
    // Promo
    "promo.title": "Promo Code",
    "promo.apply": "Apply",
    "promo.applied": "Promo code applied",
    "promo.invalid": "Invalid promo code",
    "promo.expired": "Promo code expired",
    "promo.alreadyUsed": "You have already used this promo code",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.empty": "No notifications",
    "notifications.markRead": "Mark as read",
    "notifications.markAllRead": "Mark all as read",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "ru";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
